/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.Address;
import com.rms.admin.persistence.tables.interfaces.IAddress;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record7<Long, String, String, String, String, OffsetDateTime, OffsetDateTime>, IAddress {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.address.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.address.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.address.local_address</code>.
     */
    @Override
    public void setLocalAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.address.local_address</code>.
     */
    @Override
    public String getLocalAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.address.city</code>.
     */
    @Override
    public void setCity(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.address.city</code>.
     */
    @Override
    public String getCity() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.address.state</code>.
     */
    @Override
    public void setState(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.address.state</code>.
     */
    @Override
    public String getState() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.address.country</code>.
     */
    @Override
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.address.country</code>.
     */
    @Override
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.address.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.address.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.address.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.address.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Address.ADDRESS.ID;
    }

    @Override
    public Field<String> field2() {
        return Address.ADDRESS.LOCAL_ADDRESS;
    }

    @Override
    public Field<String> field3() {
        return Address.ADDRESS.CITY;
    }

    @Override
    public Field<String> field4() {
        return Address.ADDRESS.STATE;
    }

    @Override
    public Field<String> field5() {
        return Address.ADDRESS.COUNTRY;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Address.ADDRESS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Address.ADDRESS.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLocalAddress();
    }

    @Override
    public String component3() {
        return getCity();
    }

    @Override
    public String component4() {
        return getState();
    }

    @Override
    public String component5() {
        return getCountry();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component7() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLocalAddress();
    }

    @Override
    public String value3() {
        return getCity();
    }

    @Override
    public String value4() {
        return getState();
    }

    @Override
    public String value5() {
        return getCountry();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value7() {
        return getUpdatedAt();
    }

    @Override
    public AddressRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AddressRecord value2(String value) {
        setLocalAddress(value);
        return this;
    }

    @Override
    public AddressRecord value3(String value) {
        setCity(value);
        return this;
    }

    @Override
    public AddressRecord value4(String value) {
        setState(value);
        return this;
    }

    @Override
    public AddressRecord value5(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public AddressRecord value6(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AddressRecord value7(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AddressRecord values(Long value1, String value2, String value3, String value4, String value5, OffsetDateTime value6, OffsetDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAddress from) {
        setId(from.getId());
        setLocalAddress(from.getLocalAddress());
        setCity(from.getCity());
        setState(from.getState());
        setCountry(from.getCountry());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IAddress> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Long id, String localAddress, String city, String state, String country, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Address.ADDRESS);

        setId(id);
        setLocalAddress(localAddress);
        setCity(city);
        setState(state);
        setCountry(country);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(com.rms.admin.persistence.tables.pojos.Address value) {
        super(Address.ADDRESS);

        if (value != null) {
            setId(value.getId());
            setLocalAddress(value.getLocalAddress());
            setCity(value.getCity());
            setState(value.getState());
            setCountry(value.getCountry());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
