/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.AmenitiesAssetMapping;
import com.rms.admin.persistence.tables.interfaces.IAmenitiesAssetMapping;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmenitiesAssetMappingRecord extends UpdatableRecordImpl<AmenitiesAssetMappingRecord> implements Record2<Long, Long>, IAmenitiesAssetMapping {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.amenities_asset_mapping.asset_id</code>.
     */
    @Override
    public void setAssetId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.amenities_asset_mapping.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.amenities_asset_mapping.anomaly_id</code>.
     */
    @Override
    public void setAnomalyId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.amenities_asset_mapping.anomaly_id</code>.
     */
    @Override
    public Long getAnomalyId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING.ASSET_ID;
    }

    @Override
    public Field<Long> field2() {
        return AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING.ANOMALY_ID;
    }

    @Override
    public Long component1() {
        return getAssetId();
    }

    @Override
    public Long component2() {
        return getAnomalyId();
    }

    @Override
    public Long value1() {
        return getAssetId();
    }

    @Override
    public Long value2() {
        return getAnomalyId();
    }

    @Override
    public AmenitiesAssetMappingRecord value1(Long value) {
        setAssetId(value);
        return this;
    }

    @Override
    public AmenitiesAssetMappingRecord value2(Long value) {
        setAnomalyId(value);
        return this;
    }

    @Override
    public AmenitiesAssetMappingRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAmenitiesAssetMapping from) {
        setAssetId(from.getAssetId());
        setAnomalyId(from.getAnomalyId());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IAmenitiesAssetMapping> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AmenitiesAssetMappingRecord
     */
    public AmenitiesAssetMappingRecord() {
        super(AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING);
    }

    /**
     * Create a detached, initialised AmenitiesAssetMappingRecord
     */
    public AmenitiesAssetMappingRecord(Long assetId, Long anomalyId) {
        super(AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING);

        setAssetId(assetId);
        setAnomalyId(anomalyId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AmenitiesAssetMappingRecord
     */
    public AmenitiesAssetMappingRecord(com.rms.admin.persistence.tables.pojos.AmenitiesAssetMapping value) {
        super(AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING);

        if (value != null) {
            setAssetId(value.getAssetId());
            setAnomalyId(value.getAnomalyId());
            resetChangedOnNotNull();
        }
    }
}
