/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.AssetTenantRequest;
import com.rms.admin.persistence.tables.interfaces.IAssetTenantRequest;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetTenantRequestRecord extends UpdatableRecordImpl<AssetTenantRequestRecord> implements Record4<Long, Long, String, OffsetDateTime>, IAssetTenantRequest {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_tenant_request.user_id</code>.
     */
    @Override
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset_tenant_request.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.asset_tenant_request.asset_id</code>.
     */
    @Override
    public void setAssetId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset_tenant_request.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.asset_tenant_request.type</code>.
     */
    @Override
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asset_tenant_request.type</code>.
     */
    @Override
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.asset_tenant_request.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asset_tenant_request.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<Long, Long, String, OffsetDateTime> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, String, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AssetTenantRequest.ASSET_TENANT_REQUEST.USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return AssetTenantRequest.ASSET_TENANT_REQUEST.ASSET_ID;
    }

    @Override
    public Field<String> field3() {
        return AssetTenantRequest.ASSET_TENANT_REQUEST.TYPE;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return AssetTenantRequest.ASSET_TENANT_REQUEST.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public Long component2() {
        return getAssetId();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public Long value2() {
        return getAssetId();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public AssetTenantRequestRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public AssetTenantRequestRecord value2(Long value) {
        setAssetId(value);
        return this;
    }

    @Override
    public AssetTenantRequestRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public AssetTenantRequestRecord value4(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AssetTenantRequestRecord values(Long value1, Long value2, String value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetTenantRequest from) {
        setUserId(from.getUserId());
        setAssetId(from.getAssetId());
        setType(from.getType());
        setCreatedAt(from.getCreatedAt());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IAssetTenantRequest> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetTenantRequestRecord
     */
    public AssetTenantRequestRecord() {
        super(AssetTenantRequest.ASSET_TENANT_REQUEST);
    }

    /**
     * Create a detached, initialised AssetTenantRequestRecord
     */
    public AssetTenantRequestRecord(Long userId, Long assetId, String type, OffsetDateTime createdAt) {
        super(AssetTenantRequest.ASSET_TENANT_REQUEST);

        setUserId(userId);
        setAssetId(assetId);
        setType(type);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AssetTenantRequestRecord
     */
    public AssetTenantRequestRecord(com.rms.admin.persistence.tables.pojos.AssetTenantRequest value) {
        super(AssetTenantRequest.ASSET_TENANT_REQUEST);

        if (value != null) {
            setUserId(value.getUserId());
            setAssetId(value.getAssetId());
            setType(value.getType());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
