/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.AssetImageMapping;
import com.rms.admin.persistence.tables.interfaces.IAssetImageMapping;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetImageMappingRecord extends UpdatableRecordImpl<AssetImageMappingRecord> implements Record2<Long, Long>, IAssetImageMapping {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_image_mapping.asset_id</code>.
     */
    @Override
    public void setAssetId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset_image_mapping.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.asset_image_mapping.image_id</code>.
     */
    @Override
    public void setImageId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset_image_mapping.image_id</code>.
     */
    @Override
    public Long getImageId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AssetImageMapping.ASSET_IMAGE_MAPPING.ASSET_ID;
    }

    @Override
    public Field<Long> field2() {
        return AssetImageMapping.ASSET_IMAGE_MAPPING.IMAGE_ID;
    }

    @Override
    public Long component1() {
        return getAssetId();
    }

    @Override
    public Long component2() {
        return getImageId();
    }

    @Override
    public Long value1() {
        return getAssetId();
    }

    @Override
    public Long value2() {
        return getImageId();
    }

    @Override
    public AssetImageMappingRecord value1(Long value) {
        setAssetId(value);
        return this;
    }

    @Override
    public AssetImageMappingRecord value2(Long value) {
        setImageId(value);
        return this;
    }

    @Override
    public AssetImageMappingRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetImageMapping from) {
        setAssetId(from.getAssetId());
        setImageId(from.getImageId());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IAssetImageMapping> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetImageMappingRecord
     */
    public AssetImageMappingRecord() {
        super(AssetImageMapping.ASSET_IMAGE_MAPPING);
    }

    /**
     * Create a detached, initialised AssetImageMappingRecord
     */
    public AssetImageMappingRecord(Long assetId, Long imageId) {
        super(AssetImageMapping.ASSET_IMAGE_MAPPING);

        setAssetId(assetId);
        setImageId(imageId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AssetImageMappingRecord
     */
    public AssetImageMappingRecord(com.rms.admin.persistence.tables.pojos.AssetImageMapping value) {
        super(AssetImageMapping.ASSET_IMAGE_MAPPING);

        if (value != null) {
            setAssetId(value.getAssetId());
            setImageId(value.getImageId());
            resetChangedOnNotNull();
        }
    }
}
