/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.AssetTenantMapping;
import com.rms.admin.persistence.tables.interfaces.IAssetTenantMapping;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetTenantMappingRecord extends UpdatableRecordImpl<AssetTenantMappingRecord> implements Record2<Long, Long>, IAssetTenantMapping {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_tenant_mapping.user_id</code>.
     */
    @Override
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset_tenant_mapping.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.asset_tenant_mapping.asset_id</code>.
     */
    @Override
    public void setAssetId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset_tenant_mapping.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return AssetTenantMapping.ASSET_TENANT_MAPPING.USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return AssetTenantMapping.ASSET_TENANT_MAPPING.ASSET_ID;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public Long component2() {
        return getAssetId();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public Long value2() {
        return getAssetId();
    }

    @Override
    public AssetTenantMappingRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public AssetTenantMappingRecord value2(Long value) {
        setAssetId(value);
        return this;
    }

    @Override
    public AssetTenantMappingRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetTenantMapping from) {
        setUserId(from.getUserId());
        setAssetId(from.getAssetId());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IAssetTenantMapping> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetTenantMappingRecord
     */
    public AssetTenantMappingRecord() {
        super(AssetTenantMapping.ASSET_TENANT_MAPPING);
    }

    /**
     * Create a detached, initialised AssetTenantMappingRecord
     */
    public AssetTenantMappingRecord(Long userId, Long assetId) {
        super(AssetTenantMapping.ASSET_TENANT_MAPPING);

        setUserId(userId);
        setAssetId(assetId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AssetTenantMappingRecord
     */
    public AssetTenantMappingRecord(com.rms.admin.persistence.tables.pojos.AssetTenantMapping value) {
        super(AssetTenantMapping.ASSET_TENANT_MAPPING);

        if (value != null) {
            setUserId(value.getUserId());
            setAssetId(value.getAssetId());
            resetChangedOnNotNull();
        }
    }
}
