/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.Asset;
import com.rms.admin.persistence.tables.interfaces.IAsset;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetRecord extends UpdatableRecordImpl<AssetRecord> implements Record11<Long, String, String, Long, BigDecimal, JSONB, Long, Long, Long, OffsetDateTime, OffsetDateTime>, IAsset {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.asset.title</code>.
     */
    @Override
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.asset.description</code>.
     */
    @Override
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asset.description</code>.
     */
    @Override
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.asset.capacity</code>.
     */
    @Override
    public void setCapacity(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asset.capacity</code>.
     */
    @Override
    public Long getCapacity() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.asset.rent</code>.
     */
    @Override
    public void setRent(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.asset.rent</code>.
     */
    @Override
    public BigDecimal getRent() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.asset.tags</code>.
     */
    @Override
    public void setTags(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.asset.tags</code>.
     */
    @Override
    public JSONB getTags() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.asset.category_id</code>.
     */
    @Override
    public void setCategoryId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.asset.category_id</code>.
     */
    @Override
    public Long getCategoryId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.asset.owner_id</code>.
     */
    @Override
    public void setOwnerId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.asset.owner_id</code>.
     */
    @Override
    public Long getOwnerId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.asset.location</code>.
     */
    @Override
    public void setLocation(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.asset.location</code>.
     */
    @Override
    public Long getLocation() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.asset.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.asset.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.asset.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.asset.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, Long, BigDecimal, JSONB, Long, Long, Long, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, Long, BigDecimal, JSONB, Long, Long, Long, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Asset.ASSET.ID;
    }

    @Override
    public Field<String> field2() {
        return Asset.ASSET.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Asset.ASSET.DESCRIPTION;
    }

    @Override
    public Field<Long> field4() {
        return Asset.ASSET.CAPACITY;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Asset.ASSET.RENT;
    }

    @Override
    public Field<JSONB> field6() {
        return Asset.ASSET.TAGS;
    }

    @Override
    public Field<Long> field7() {
        return Asset.ASSET.CATEGORY_ID;
    }

    @Override
    public Field<Long> field8() {
        return Asset.ASSET.OWNER_ID;
    }

    @Override
    public Field<Long> field9() {
        return Asset.ASSET.LOCATION;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return Asset.ASSET.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field11() {
        return Asset.ASSET.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Long component4() {
        return getCapacity();
    }

    @Override
    public BigDecimal component5() {
        return getRent();
    }

    @Override
    public JSONB component6() {
        return getTags();
    }

    @Override
    public Long component7() {
        return getCategoryId();
    }

    @Override
    public Long component8() {
        return getOwnerId();
    }

    @Override
    public Long component9() {
        return getLocation();
    }

    @Override
    public OffsetDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component11() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Long value4() {
        return getCapacity();
    }

    @Override
    public BigDecimal value5() {
        return getRent();
    }

    @Override
    public JSONB value6() {
        return getTags();
    }

    @Override
    public Long value7() {
        return getCategoryId();
    }

    @Override
    public Long value8() {
        return getOwnerId();
    }

    @Override
    public Long value9() {
        return getLocation();
    }

    @Override
    public OffsetDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value11() {
        return getUpdatedAt();
    }

    @Override
    public AssetRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AssetRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public AssetRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AssetRecord value4(Long value) {
        setCapacity(value);
        return this;
    }

    @Override
    public AssetRecord value5(BigDecimal value) {
        setRent(value);
        return this;
    }

    @Override
    public AssetRecord value6(JSONB value) {
        setTags(value);
        return this;
    }

    @Override
    public AssetRecord value7(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public AssetRecord value8(Long value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public AssetRecord value9(Long value) {
        setLocation(value);
        return this;
    }

    @Override
    public AssetRecord value10(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AssetRecord value11(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AssetRecord values(Long value1, String value2, String value3, Long value4, BigDecimal value5, JSONB value6, Long value7, Long value8, Long value9, OffsetDateTime value10, OffsetDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAsset from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setCapacity(from.getCapacity());
        setRent(from.getRent());
        setTags(from.getTags());
        setCategoryId(from.getCategoryId());
        setOwnerId(from.getOwnerId());
        setLocation(from.getLocation());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IAsset> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetRecord
     */
    public AssetRecord() {
        super(Asset.ASSET);
    }

    /**
     * Create a detached, initialised AssetRecord
     */
    public AssetRecord(Long id, String title, String description, Long capacity, BigDecimal rent, JSONB tags, Long categoryId, Long ownerId, Long location, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Asset.ASSET);

        setId(id);
        setTitle(title);
        setDescription(description);
        setCapacity(capacity);
        setRent(rent);
        setTags(tags);
        setCategoryId(categoryId);
        setOwnerId(ownerId);
        setLocation(location);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AssetRecord
     */
    public AssetRecord(com.rms.admin.persistence.tables.pojos.Asset value) {
        super(Asset.ASSET);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setDescription(value.getDescription());
            setCapacity(value.getCapacity());
            setRent(value.getRent());
            setTags(value.getTags());
            setCategoryId(value.getCategoryId());
            setOwnerId(value.getOwnerId());
            setLocation(value.getLocation());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
