/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.EmailTemplates;
import com.rms.admin.persistence.tables.interfaces.IEmailTemplates;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailTemplatesRecord extends UpdatableRecordImpl<EmailTemplatesRecord> implements Record6<Long, String, String, JSONB, OffsetDateTime, OffsetDateTime>, IEmailTemplates {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.email_templates.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.email_templates.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.email_templates.subject</code>.
     */
    @Override
    public void setSubject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.email_templates.subject</code>.
     */
    @Override
    public String getSubject() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.email_templates.template</code>.
     */
    @Override
    public void setTemplate(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.email_templates.template</code>.
     */
    @Override
    public String getTemplate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.email_templates.placeholder_values</code>.
     */
    @Override
    public void setPlaceholderValues(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.email_templates.placeholder_values</code>.
     */
    @Override
    public JSONB getPlaceholderValues() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.email_templates.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.email_templates.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.email_templates.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.email_templates.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, JSONB, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, JSONB, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return EmailTemplates.EMAIL_TEMPLATES.ID;
    }

    @Override
    public Field<String> field2() {
        return EmailTemplates.EMAIL_TEMPLATES.SUBJECT;
    }

    @Override
    public Field<String> field3() {
        return EmailTemplates.EMAIL_TEMPLATES.TEMPLATE;
    }

    @Override
    public Field<JSONB> field4() {
        return EmailTemplates.EMAIL_TEMPLATES.PLACEHOLDER_VALUES;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return EmailTemplates.EMAIL_TEMPLATES.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return EmailTemplates.EMAIL_TEMPLATES.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSubject();
    }

    @Override
    public String component3() {
        return getTemplate();
    }

    @Override
    public JSONB component4() {
        return getPlaceholderValues();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSubject();
    }

    @Override
    public String value3() {
        return getTemplate();
    }

    @Override
    public JSONB value4() {
        return getPlaceholderValues();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public EmailTemplatesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EmailTemplatesRecord value2(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public EmailTemplatesRecord value3(String value) {
        setTemplate(value);
        return this;
    }

    @Override
    public EmailTemplatesRecord value4(JSONB value) {
        setPlaceholderValues(value);
        return this;
    }

    @Override
    public EmailTemplatesRecord value5(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EmailTemplatesRecord value6(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public EmailTemplatesRecord values(Long value1, String value2, String value3, JSONB value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IEmailTemplates from) {
        setId(from.getId());
        setSubject(from.getSubject());
        setTemplate(from.getTemplate());
        setPlaceholderValues(from.getPlaceholderValues());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IEmailTemplates> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailTemplatesRecord
     */
    public EmailTemplatesRecord() {
        super(EmailTemplates.EMAIL_TEMPLATES);
    }

    /**
     * Create a detached, initialised EmailTemplatesRecord
     */
    public EmailTemplatesRecord(Long id, String subject, String template, JSONB placeholderValues, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(EmailTemplates.EMAIL_TEMPLATES);

        setId(id);
        setSubject(subject);
        setTemplate(template);
        setPlaceholderValues(placeholderValues);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EmailTemplatesRecord
     */
    public EmailTemplatesRecord(com.rms.admin.persistence.tables.pojos.EmailTemplates value) {
        super(EmailTemplates.EMAIL_TEMPLATES);

        if (value != null) {
            setId(value.getId());
            setSubject(value.getSubject());
            setTemplate(value.getTemplate());
            setPlaceholderValues(value.getPlaceholderValues());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
