/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.Notifications;
import com.rms.admin.persistence.tables.interfaces.INotifications;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationsRecord extends UpdatableRecordImpl<NotificationsRecord> implements Record6<Long, Long, String, Boolean, OffsetDateTime, OffsetDateTime>, INotifications {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notifications.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notifications.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.notifications.user_id</code>.
     */
    @Override
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notifications.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.notifications.message</code>.
     */
    @Override
    public void setMessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notifications.message</code>.
     */
    @Override
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.notifications.is_read</code>.
     */
    @Override
    public void setIsRead(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notifications.is_read</code>.
     */
    @Override
    public Boolean getIsRead() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.notifications.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notifications.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.notifications.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notifications.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, Boolean, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, Boolean, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Notifications.NOTIFICATIONS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Notifications.NOTIFICATIONS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Notifications.NOTIFICATIONS.MESSAGE;
    }

    @Override
    public Field<Boolean> field4() {
        return Notifications.NOTIFICATIONS.IS_READ;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Notifications.NOTIFICATIONS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Notifications.NOTIFICATIONS.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getMessage();
    }

    @Override
    public Boolean component4() {
        return getIsRead();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getMessage();
    }

    @Override
    public Boolean value4() {
        return getIsRead();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public NotificationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationsRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public NotificationsRecord value3(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public NotificationsRecord value4(Boolean value) {
        setIsRead(value);
        return this;
    }

    @Override
    public NotificationsRecord value5(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public NotificationsRecord value6(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public NotificationsRecord values(Long value1, Long value2, String value3, Boolean value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(INotifications from) {
        setId(from.getId());
        setUserId(from.getUserId());
        setMessage(from.getMessage());
        setIsRead(from.getIsRead());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends INotifications> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationsRecord
     */
    public NotificationsRecord() {
        super(Notifications.NOTIFICATIONS);
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(Long id, Long userId, String message, Boolean isRead, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Notifications.NOTIFICATIONS);

        setId(id);
        setUserId(userId);
        setMessage(message);
        setIsRead(isRead);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(com.rms.admin.persistence.tables.pojos.Notifications value) {
        super(Notifications.NOTIFICATIONS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setMessage(value.getMessage());
            setIsRead(value.getIsRead());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
