/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.records;


import com.rms.admin.persistence.tables.Users;
import com.rms.admin.persistence.tables.interfaces.IUsers;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record12<Long, Long, String, String, String, String, String, Long, Long, Boolean, OffsetDateTime, OffsetDateTime>, IUsers {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    @Override
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.image_id</code>.
     */
    @Override
    public void setImageId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.image_id</code>.
     */
    @Override
    public Long getImageId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    @Override
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    @Override
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    @Override
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    @Override
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.jwt_secret</code>.
     */
    @Override
    public void setJwtSecret(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.jwt_secret</code>.
     */
    @Override
    public String getJwtSecret() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.phone_no</code>.
     */
    @Override
    public void setPhoneNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.phone_no</code>.
     */
    @Override
    public String getPhoneNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.role_id</code>.
     */
    @Override
    public void setRoleId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.role_id</code>.
     */
    @Override
    public Long getRoleId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.users.address_id</code>.
     */
    @Override
    public void setAddressId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.address_id</code>.
     */
    @Override
    public Long getAddressId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.users.is_verified</code>.
     */
    @Override
    public void setIsVerified(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.is_verified</code>.
     */
    @Override
    public Boolean getIsVerified() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, String, String, String, String, String, Long, Long, Boolean, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, String, String, String, String, String, Long, Long, Boolean, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Users.USERS.IMAGE_ID;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return Users.USERS.JWT_SECRET;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.PHONE_NO;
    }

    @Override
    public Field<Long> field8() {
        return Users.USERS.ROLE_ID;
    }

    @Override
    public Field<Long> field9() {
        return Users.USERS.ADDRESS_ID;
    }

    @Override
    public Field<Boolean> field10() {
        return Users.USERS.IS_VERIFIED;
    }

    @Override
    public Field<OffsetDateTime> field11() {
        return Users.USERS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field12() {
        return Users.USERS.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getImageId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getJwtSecret();
    }

    @Override
    public String component7() {
        return getPhoneNo();
    }

    @Override
    public Long component8() {
        return getRoleId();
    }

    @Override
    public Long component9() {
        return getAddressId();
    }

    @Override
    public Boolean component10() {
        return getIsVerified();
    }

    @Override
    public OffsetDateTime component11() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component12() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getImageId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getJwtSecret();
    }

    @Override
    public String value7() {
        return getPhoneNo();
    }

    @Override
    public Long value8() {
        return getRoleId();
    }

    @Override
    public Long value9() {
        return getAddressId();
    }

    @Override
    public Boolean value10() {
        return getIsVerified();
    }

    @Override
    public OffsetDateTime value11() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value12() {
        return getUpdatedAt();
    }

    @Override
    public UsersRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(Long value) {
        setImageId(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UsersRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value6(String value) {
        setJwtSecret(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setPhoneNo(value);
        return this;
    }

    @Override
    public UsersRecord value8(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public UsersRecord value9(Long value) {
        setAddressId(value);
        return this;
    }

    @Override
    public UsersRecord value10(Boolean value) {
        setIsVerified(value);
        return this;
    }

    @Override
    public UsersRecord value11(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UsersRecord value12(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UsersRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, Long value8, Long value9, Boolean value10, OffsetDateTime value11, OffsetDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUsers from) {
        setId(from.getId());
        setImageId(from.getImageId());
        setName(from.getName());
        setEmail(from.getEmail());
        setPassword(from.getPassword());
        setJwtSecret(from.getJwtSecret());
        setPhoneNo(from.getPhoneNo());
        setRoleId(from.getRoleId());
        setAddressId(from.getAddressId());
        setIsVerified(from.getIsVerified());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
        resetChangedOnNotNull();
    }

    @Override
    public <E extends IUsers> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, Long imageId, String name, String email, String password, String jwtSecret, String phoneNo, Long roleId, Long addressId, Boolean isVerified, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Users.USERS);

        setId(id);
        setImageId(imageId);
        setName(name);
        setEmail(email);
        setPassword(password);
        setJwtSecret(jwtSecret);
        setPhoneNo(phoneNo);
        setRoleId(roleId);
        setAddressId(addressId);
        setIsVerified(isVerified);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(com.rms.admin.persistence.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setImageId(value.getImageId());
            setName(value.getName());
            setEmail(value.getEmail());
            setPassword(value.getPassword());
            setJwtSecret(value.getJwtSecret());
            setPhoneNo(value.getPhoneNo());
            setRoleId(value.getRoleId());
            setAddressId(value.getAddressId());
            setIsVerified(value.getIsVerified());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
