/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.AmenitiesAssetMappingRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmenitiesAssetMapping extends TableImpl<AmenitiesAssetMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.amenities_asset_mapping</code>
     */
    public static final AmenitiesAssetMapping AMENITIES_ASSET_MAPPING = new AmenitiesAssetMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmenitiesAssetMappingRecord> getRecordType() {
        return AmenitiesAssetMappingRecord.class;
    }

    /**
     * The column <code>public.amenities_asset_mapping.asset_id</code>.
     */
    public final TableField<AmenitiesAssetMappingRecord, Long> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.amenities_asset_mapping.anomaly_id</code>.
     */
    public final TableField<AmenitiesAssetMappingRecord, Long> ANOMALY_ID = createField(DSL.name("anomaly_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AmenitiesAssetMapping(Name alias, Table<AmenitiesAssetMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private AmenitiesAssetMapping(Name alias, Table<AmenitiesAssetMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.amenities_asset_mapping</code> table
     * reference
     */
    public AmenitiesAssetMapping(String alias) {
        this(DSL.name(alias), AMENITIES_ASSET_MAPPING);
    }

    /**
     * Create an aliased <code>public.amenities_asset_mapping</code> table
     * reference
     */
    public AmenitiesAssetMapping(Name alias) {
        this(alias, AMENITIES_ASSET_MAPPING);
    }

    /**
     * Create a <code>public.amenities_asset_mapping</code> table reference
     */
    public AmenitiesAssetMapping() {
        this(DSL.name("amenities_asset_mapping"), null);
    }

    public <O extends Record> AmenitiesAssetMapping(Table<O> child, ForeignKey<O, AmenitiesAssetMappingRecord> key) {
        super(child, key, AMENITIES_ASSET_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AmenitiesAssetMappingRecord> getPrimaryKey() {
        return Keys.AMENITIES_ASSET_MAPPING_PKEY;
    }

    @Override
    public List<ForeignKey<AmenitiesAssetMappingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AMENITIES_ASSET_MAPPING__FK_AMENITIES_ASSET_MAPPING_ASSET, Keys.AMENITIES_ASSET_MAPPING__FK_AMENITIES_ASSET_MAPPING_ANOMALY);
    }

    private transient Asset _asset;
    private transient Amenities _amenities;

    /**
     * Get the implicit join path to the <code>public.asset</code> table.
     */
    public Asset asset() {
        if (_asset == null)
            _asset = new Asset(this, Keys.AMENITIES_ASSET_MAPPING__FK_AMENITIES_ASSET_MAPPING_ASSET);

        return _asset;
    }

    /**
     * Get the implicit join path to the <code>public.amenities</code> table.
     */
    public Amenities amenities() {
        if (_amenities == null)
            _amenities = new Amenities(this, Keys.AMENITIES_ASSET_MAPPING__FK_AMENITIES_ASSET_MAPPING_ANOMALY);

        return _amenities;
    }

    @Override
    public AmenitiesAssetMapping as(String alias) {
        return new AmenitiesAssetMapping(DSL.name(alias), this);
    }

    @Override
    public AmenitiesAssetMapping as(Name alias) {
        return new AmenitiesAssetMapping(alias, this);
    }

    @Override
    public AmenitiesAssetMapping as(Table<?> alias) {
        return new AmenitiesAssetMapping(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AmenitiesAssetMapping rename(String name) {
        return new AmenitiesAssetMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmenitiesAssetMapping rename(Name name) {
        return new AmenitiesAssetMapping(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AmenitiesAssetMapping rename(Table<?> name) {
        return new AmenitiesAssetMapping(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
