/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.AmenitiesRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Amenities extends TableImpl<AmenitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.amenities</code>
     */
    public static final Amenities AMENITIES = new Amenities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AmenitiesRecord> getRecordType() {
        return AmenitiesRecord.class;
    }

    /**
     * The column <code>public.amenities.id</code>.
     */
    public final TableField<AmenitiesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.amenities.name</code>.
     */
    public final TableField<AmenitiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.amenities.created_at</code>.
     */
    public final TableField<AmenitiesRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.amenities.updated_at</code>.
     */
    public final TableField<AmenitiesRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Amenities(Name alias, Table<AmenitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Amenities(Name alias, Table<AmenitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.amenities</code> table reference
     */
    public Amenities(String alias) {
        this(DSL.name(alias), AMENITIES);
    }

    /**
     * Create an aliased <code>public.amenities</code> table reference
     */
    public Amenities(Name alias) {
        this(alias, AMENITIES);
    }

    /**
     * Create a <code>public.amenities</code> table reference
     */
    public Amenities() {
        this(DSL.name("amenities"), null);
    }

    public <O extends Record> Amenities(Table<O> child, ForeignKey<O, AmenitiesRecord> key) {
        super(child, key, AMENITIES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AmenitiesRecord, Long> getIdentity() {
        return (Identity<AmenitiesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AmenitiesRecord> getPrimaryKey() {
        return Keys.AMENITIES_PKEY;
    }

    @Override
    public List<UniqueKey<AmenitiesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AMENITIES_NAME_KEY);
    }

    @Override
    public Amenities as(String alias) {
        return new Amenities(DSL.name(alias), this);
    }

    @Override
    public Amenities as(Name alias) {
        return new Amenities(alias, this);
    }

    @Override
    public Amenities as(Table<?> alias) {
        return new Amenities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Amenities rename(String name) {
        return new Amenities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Amenities rename(Name name) {
        return new Amenities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Amenities rename(Table<?> name) {
        return new Amenities(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
