/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.AssetTenantMappingRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetTenantMapping extends TableImpl<AssetTenantMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.asset_tenant_mapping</code>
     */
    public static final AssetTenantMapping ASSET_TENANT_MAPPING = new AssetTenantMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssetTenantMappingRecord> getRecordType() {
        return AssetTenantMappingRecord.class;
    }

    /**
     * The column <code>public.asset_tenant_mapping.user_id</code>.
     */
    public final TableField<AssetTenantMappingRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.asset_tenant_mapping.asset_id</code>.
     */
    public final TableField<AssetTenantMappingRecord, Long> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AssetTenantMapping(Name alias, Table<AssetTenantMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private AssetTenantMapping(Name alias, Table<AssetTenantMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.asset_tenant_mapping</code> table
     * reference
     */
    public AssetTenantMapping(String alias) {
        this(DSL.name(alias), ASSET_TENANT_MAPPING);
    }

    /**
     * Create an aliased <code>public.asset_tenant_mapping</code> table
     * reference
     */
    public AssetTenantMapping(Name alias) {
        this(alias, ASSET_TENANT_MAPPING);
    }

    /**
     * Create a <code>public.asset_tenant_mapping</code> table reference
     */
    public AssetTenantMapping() {
        this(DSL.name("asset_tenant_mapping"), null);
    }

    public <O extends Record> AssetTenantMapping(Table<O> child, ForeignKey<O, AssetTenantMappingRecord> key) {
        super(child, key, ASSET_TENANT_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AssetTenantMappingRecord> getPrimaryKey() {
        return Keys.ASSET_TENANT_MAPPING_PKEY;
    }

    @Override
    public List<ForeignKey<AssetTenantMappingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSET_TENANT_MAPPING__FK_ASSET_TENANT_MAPPING_USER, Keys.ASSET_TENANT_MAPPING__FK_ASSET_TENANT_MAPPING_ASSET);
    }

    private transient Users _users;
    private transient Asset _asset;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.ASSET_TENANT_MAPPING__FK_ASSET_TENANT_MAPPING_USER);

        return _users;
    }

    /**
     * Get the implicit join path to the <code>public.asset</code> table.
     */
    public Asset asset() {
        if (_asset == null)
            _asset = new Asset(this, Keys.ASSET_TENANT_MAPPING__FK_ASSET_TENANT_MAPPING_ASSET);

        return _asset;
    }

    @Override
    public AssetTenantMapping as(String alias) {
        return new AssetTenantMapping(DSL.name(alias), this);
    }

    @Override
    public AssetTenantMapping as(Name alias) {
        return new AssetTenantMapping(alias, this);
    }

    @Override
    public AssetTenantMapping as(Table<?> alias) {
        return new AssetTenantMapping(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetTenantMapping rename(String name) {
        return new AssetTenantMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetTenantMapping rename(Name name) {
        return new AssetTenantMapping(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetTenantMapping rename(Table<?> name) {
        return new AssetTenantMapping(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
