/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.AssetTenantRequestRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetTenantRequest extends TableImpl<AssetTenantRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.asset_tenant_request</code>
     */
    public static final AssetTenantRequest ASSET_TENANT_REQUEST = new AssetTenantRequest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssetTenantRequestRecord> getRecordType() {
        return AssetTenantRequestRecord.class;
    }

    /**
     * The column <code>public.asset_tenant_request.user_id</code>.
     */
    public final TableField<AssetTenantRequestRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.asset_tenant_request.asset_id</code>.
     */
    public final TableField<AssetTenantRequestRecord, Long> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.asset_tenant_request.type</code>.
     */
    public final TableField<AssetTenantRequestRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.inline("REQUEST", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.asset_tenant_request.created_at</code>.
     */
    public final TableField<AssetTenantRequestRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AssetTenantRequest(Name alias, Table<AssetTenantRequestRecord> aliased) {
        this(alias, aliased, null);
    }

    private AssetTenantRequest(Name alias, Table<AssetTenantRequestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.asset_tenant_request</code> table
     * reference
     */
    public AssetTenantRequest(String alias) {
        this(DSL.name(alias), ASSET_TENANT_REQUEST);
    }

    /**
     * Create an aliased <code>public.asset_tenant_request</code> table
     * reference
     */
    public AssetTenantRequest(Name alias) {
        this(alias, ASSET_TENANT_REQUEST);
    }

    /**
     * Create a <code>public.asset_tenant_request</code> table reference
     */
    public AssetTenantRequest() {
        this(DSL.name("asset_tenant_request"), null);
    }

    public <O extends Record> AssetTenantRequest(Table<O> child, ForeignKey<O, AssetTenantRequestRecord> key) {
        super(child, key, ASSET_TENANT_REQUEST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AssetTenantRequestRecord> getPrimaryKey() {
        return Keys.ASSET_TENANT_REQUEST_PKEY;
    }

    @Override
    public List<ForeignKey<AssetTenantRequestRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSET_TENANT_REQUEST__FK_ASSET_TENANT_REQUEST_USER, Keys.ASSET_TENANT_REQUEST__FK_ASSET_TENANT_REQUEST_ASSET);
    }

    private transient Users _users;
    private transient Asset _asset;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.ASSET_TENANT_REQUEST__FK_ASSET_TENANT_REQUEST_USER);

        return _users;
    }

    /**
     * Get the implicit join path to the <code>public.asset</code> table.
     */
    public Asset asset() {
        if (_asset == null)
            _asset = new Asset(this, Keys.ASSET_TENANT_REQUEST__FK_ASSET_TENANT_REQUEST_ASSET);

        return _asset;
    }

    @Override
    public AssetTenantRequest as(String alias) {
        return new AssetTenantRequest(DSL.name(alias), this);
    }

    @Override
    public AssetTenantRequest as(Name alias) {
        return new AssetTenantRequest(alias, this);
    }

    @Override
    public AssetTenantRequest as(Table<?> alias) {
        return new AssetTenantRequest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetTenantRequest rename(String name) {
        return new AssetTenantRequest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetTenantRequest rename(Name name) {
        return new AssetTenantRequest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetTenantRequest rename(Table<?> name) {
        return new AssetTenantRequest(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super Long, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super Long, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
