/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.AssetImageMappingRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetImageMapping extends TableImpl<AssetImageMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.asset_image_mapping</code>
     */
    public static final AssetImageMapping ASSET_IMAGE_MAPPING = new AssetImageMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssetImageMappingRecord> getRecordType() {
        return AssetImageMappingRecord.class;
    }

    /**
     * The column <code>public.asset_image_mapping.asset_id</code>.
     */
    public final TableField<AssetImageMappingRecord, Long> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.asset_image_mapping.image_id</code>.
     */
    public final TableField<AssetImageMappingRecord, Long> IMAGE_ID = createField(DSL.name("image_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AssetImageMapping(Name alias, Table<AssetImageMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private AssetImageMapping(Name alias, Table<AssetImageMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.asset_image_mapping</code> table reference
     */
    public AssetImageMapping(String alias) {
        this(DSL.name(alias), ASSET_IMAGE_MAPPING);
    }

    /**
     * Create an aliased <code>public.asset_image_mapping</code> table reference
     */
    public AssetImageMapping(Name alias) {
        this(alias, ASSET_IMAGE_MAPPING);
    }

    /**
     * Create a <code>public.asset_image_mapping</code> table reference
     */
    public AssetImageMapping() {
        this(DSL.name("asset_image_mapping"), null);
    }

    public <O extends Record> AssetImageMapping(Table<O> child, ForeignKey<O, AssetImageMappingRecord> key) {
        super(child, key, ASSET_IMAGE_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AssetImageMappingRecord> getPrimaryKey() {
        return Keys.ASSET_IMAGE_MAPPING_PKEY;
    }

    @Override
    public List<ForeignKey<AssetImageMappingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSET_IMAGE_MAPPING__FK_ASSET_IMAGE_MAPPING_ASSET, Keys.ASSET_IMAGE_MAPPING__FK_ASSET_IMAGE_MAPPING_IMAGE);
    }

    private transient Asset _asset;
    private transient Images _images;

    /**
     * Get the implicit join path to the <code>public.asset</code> table.
     */
    public Asset asset() {
        if (_asset == null)
            _asset = new Asset(this, Keys.ASSET_IMAGE_MAPPING__FK_ASSET_IMAGE_MAPPING_ASSET);

        return _asset;
    }

    /**
     * Get the implicit join path to the <code>public.images</code> table.
     */
    public Images images() {
        if (_images == null)
            _images = new Images(this, Keys.ASSET_IMAGE_MAPPING__FK_ASSET_IMAGE_MAPPING_IMAGE);

        return _images;
    }

    @Override
    public AssetImageMapping as(String alias) {
        return new AssetImageMapping(DSL.name(alias), this);
    }

    @Override
    public AssetImageMapping as(Name alias) {
        return new AssetImageMapping(alias, this);
    }

    @Override
    public AssetImageMapping as(Table<?> alias) {
        return new AssetImageMapping(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetImageMapping rename(String name) {
        return new AssetImageMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetImageMapping rename(Name name) {
        return new AssetImageMapping(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetImageMapping rename(Table<?> name) {
        return new AssetImageMapping(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
