/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.AssetRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asset extends TableImpl<AssetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.asset</code>
     */
    public static final Asset ASSET = new Asset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssetRecord> getRecordType() {
        return AssetRecord.class;
    }

    /**
     * The column <code>public.asset.id</code>.
     */
    public final TableField<AssetRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.asset.title</code>.
     */
    public final TableField<AssetRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.asset.description</code>.
     */
    public final TableField<AssetRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.asset.capacity</code>.
     */
    public final TableField<AssetRecord, Long> CAPACITY = createField(DSL.name("capacity"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.asset.rent</code>.
     */
    public final TableField<AssetRecord, BigDecimal> RENT = createField(DSL.name("rent"), SQLDataType.NUMERIC(10, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>public.asset.tags</code>.
     */
    public final TableField<AssetRecord, JSONB> TAGS = createField(DSL.name("tags"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.asset.category_id</code>.
     */
    public final TableField<AssetRecord, Long> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.asset.owner_id</code>.
     */
    public final TableField<AssetRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.asset.location</code>.
     */
    public final TableField<AssetRecord, Long> LOCATION = createField(DSL.name("location"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.asset.created_at</code>.
     */
    public final TableField<AssetRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.asset.updated_at</code>.
     */
    public final TableField<AssetRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Asset(Name alias, Table<AssetRecord> aliased) {
        this(alias, aliased, null);
    }

    private Asset(Name alias, Table<AssetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.asset</code> table reference
     */
    public Asset(String alias) {
        this(DSL.name(alias), ASSET);
    }

    /**
     * Create an aliased <code>public.asset</code> table reference
     */
    public Asset(Name alias) {
        this(alias, ASSET);
    }

    /**
     * Create a <code>public.asset</code> table reference
     */
    public Asset() {
        this(DSL.name("asset"), null);
    }

    public <O extends Record> Asset(Table<O> child, ForeignKey<O, AssetRecord> key) {
        super(child, key, ASSET);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AssetRecord, Long> getIdentity() {
        return (Identity<AssetRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AssetRecord> getPrimaryKey() {
        return Keys.ASSET_PKEY;
    }

    @Override
    public List<ForeignKey<AssetRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSET__FK_ASSET_CATEGORY, Keys.ASSET__FK_ASSET_OWNER, Keys.ASSET__FK_ASSET_LOCATION);
    }

    private transient Category _category;
    private transient Users _users;
    private transient Address _address;

    /**
     * Get the implicit join path to the <code>public.category</code> table.
     */
    public Category category() {
        if (_category == null)
            _category = new Category(this, Keys.ASSET__FK_ASSET_CATEGORY);

        return _category;
    }

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.ASSET__FK_ASSET_OWNER);

        return _users;
    }

    /**
     * Get the implicit join path to the <code>public.address</code> table.
     */
    public Address address() {
        if (_address == null)
            _address = new Address(this, Keys.ASSET__FK_ASSET_LOCATION);

        return _address;
    }

    @Override
    public Asset as(String alias) {
        return new Asset(DSL.name(alias), this);
    }

    @Override
    public Asset as(Name alias) {
        return new Asset(alias, this);
    }

    @Override
    public Asset as(Table<?> alias) {
        return new Asset(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Asset rename(String name) {
        return new Asset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Asset rename(Name name) {
        return new Asset(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Asset rename(Table<?> name) {
        return new Asset(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, Long, BigDecimal, JSONB, Long, Long, Long, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super Long, ? super String, ? super String, ? super Long, ? super BigDecimal, ? super JSONB, ? super Long, ? super Long, ? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super Long, ? super String, ? super String, ? super Long, ? super BigDecimal, ? super JSONB, ? super Long, ? super Long, ? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
