/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.EmailTemplatesRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailTemplates extends TableImpl<EmailTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.email_templates</code>
     */
    public static final EmailTemplates EMAIL_TEMPLATES = new EmailTemplates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailTemplatesRecord> getRecordType() {
        return EmailTemplatesRecord.class;
    }

    /**
     * The column <code>public.email_templates.id</code>.
     */
    public final TableField<EmailTemplatesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.email_templates.subject</code>.
     */
    public final TableField<EmailTemplatesRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.email_templates.template</code>.
     */
    public final TableField<EmailTemplatesRecord, String> TEMPLATE = createField(DSL.name("template"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.email_templates.placeholder_values</code>.
     */
    public final TableField<EmailTemplatesRecord, JSONB> PLACEHOLDER_VALUES = createField(DSL.name("placeholder_values"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.email_templates.created_at</code>.
     */
    public final TableField<EmailTemplatesRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.email_templates.updated_at</code>.
     */
    public final TableField<EmailTemplatesRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private EmailTemplates(Name alias, Table<EmailTemplatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmailTemplates(Name alias, Table<EmailTemplatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.email_templates</code> table reference
     */
    public EmailTemplates(String alias) {
        this(DSL.name(alias), EMAIL_TEMPLATES);
    }

    /**
     * Create an aliased <code>public.email_templates</code> table reference
     */
    public EmailTemplates(Name alias) {
        this(alias, EMAIL_TEMPLATES);
    }

    /**
     * Create a <code>public.email_templates</code> table reference
     */
    public EmailTemplates() {
        this(DSL.name("email_templates"), null);
    }

    public <O extends Record> EmailTemplates(Table<O> child, ForeignKey<O, EmailTemplatesRecord> key) {
        super(child, key, EMAIL_TEMPLATES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EmailTemplatesRecord, Long> getIdentity() {
        return (Identity<EmailTemplatesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmailTemplatesRecord> getPrimaryKey() {
        return Keys.EMAIL_TEMPLATES_PKEY;
    }

    @Override
    public List<UniqueKey<EmailTemplatesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.EMAIL_TEMPLATES_SUBJECT_KEY);
    }

    @Override
    public EmailTemplates as(String alias) {
        return new EmailTemplates(DSL.name(alias), this);
    }

    @Override
    public EmailTemplates as(Name alias) {
        return new EmailTemplates(alias, this);
    }

    @Override
    public EmailTemplates as(Table<?> alias) {
        return new EmailTemplates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailTemplates rename(String name) {
        return new EmailTemplates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailTemplates rename(Name name) {
        return new EmailTemplates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailTemplates rename(Table<?> name) {
        return new EmailTemplates(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, JSONB, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super String, ? super JSONB, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super String, ? super JSONB, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
