/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.NotificationTemplatesRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationTemplates extends TableImpl<NotificationTemplatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.notification_templates</code>
     */
    public static final NotificationTemplates NOTIFICATION_TEMPLATES = new NotificationTemplates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationTemplatesRecord> getRecordType() {
        return NotificationTemplatesRecord.class;
    }

    /**
     * The column <code>public.notification_templates.id</code>.
     */
    public final TableField<NotificationTemplatesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.notification_templates.title</code>.
     */
    public final TableField<NotificationTemplatesRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.notification_templates.template</code>.
     */
    public final TableField<NotificationTemplatesRecord, String> TEMPLATE = createField(DSL.name("template"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.notification_templates.placeholder_values</code>.
     */
    public final TableField<NotificationTemplatesRecord, JSONB> PLACEHOLDER_VALUES = createField(DSL.name("placeholder_values"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.notification_templates.created_at</code>.
     */
    public final TableField<NotificationTemplatesRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.notification_templates.updated_at</code>.
     */
    public final TableField<NotificationTemplatesRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private NotificationTemplates(Name alias, Table<NotificationTemplatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotificationTemplates(Name alias, Table<NotificationTemplatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.notification_templates</code> table
     * reference
     */
    public NotificationTemplates(String alias) {
        this(DSL.name(alias), NOTIFICATION_TEMPLATES);
    }

    /**
     * Create an aliased <code>public.notification_templates</code> table
     * reference
     */
    public NotificationTemplates(Name alias) {
        this(alias, NOTIFICATION_TEMPLATES);
    }

    /**
     * Create a <code>public.notification_templates</code> table reference
     */
    public NotificationTemplates() {
        this(DSL.name("notification_templates"), null);
    }

    public <O extends Record> NotificationTemplates(Table<O> child, ForeignKey<O, NotificationTemplatesRecord> key) {
        super(child, key, NOTIFICATION_TEMPLATES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<NotificationTemplatesRecord, Long> getIdentity() {
        return (Identity<NotificationTemplatesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<NotificationTemplatesRecord> getPrimaryKey() {
        return Keys.NOTIFICATION_TEMPLATES_PKEY;
    }

    @Override
    public List<UniqueKey<NotificationTemplatesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.NOTIFICATION_TEMPLATES_TITLE_KEY);
    }

    @Override
    public NotificationTemplates as(String alias) {
        return new NotificationTemplates(DSL.name(alias), this);
    }

    @Override
    public NotificationTemplates as(Name alias) {
        return new NotificationTemplates(alias, this);
    }

    @Override
    public NotificationTemplates as(Table<?> alias) {
        return new NotificationTemplates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationTemplates rename(String name) {
        return new NotificationTemplates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationTemplates rename(Name name) {
        return new NotificationTemplates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationTemplates rename(Table<?> name) {
        return new NotificationTemplates(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, JSONB, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super String, ? super JSONB, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super String, ? super JSONB, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
