/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.PaymentOptionsRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentOptions extends TableImpl<PaymentOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.payment_options</code>
     */
    public static final PaymentOptions PAYMENT_OPTIONS = new PaymentOptions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentOptionsRecord> getRecordType() {
        return PaymentOptionsRecord.class;
    }

    /**
     * The column <code>public.payment_options.id</code>.
     */
    public final TableField<PaymentOptionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.payment_options.asset_id</code>.
     */
    public final TableField<PaymentOptionsRecord, Long> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.payment_options.owner_id</code>.
     */
    public final TableField<PaymentOptionsRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.payment_options.name</code>.
     */
    public final TableField<PaymentOptionsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.payment_options.description</code>.
     */
    public final TableField<PaymentOptionsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.payment_options.amount</code>.
     */
    public final TableField<PaymentOptionsRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "");

    /**
     * The column <code>public.payment_options.currency</code>.
     */
    public final TableField<PaymentOptionsRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(3).nullable(false).defaultValue(DSL.field(DSL.raw("'USD'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.payment_options.payment_type</code>.
     */
    public final TableField<PaymentOptionsRecord, String> PAYMENT_TYPE = createField(DSL.name("payment_type"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("'RENT'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.payment_options.is_recurring</code>.
     */
    public final TableField<PaymentOptionsRecord, Boolean> IS_RECURRING = createField(DSL.name("is_recurring"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.payment_options.recurring_interval</code>.
     */
    public final TableField<PaymentOptionsRecord, String> RECURRING_INTERVAL = createField(DSL.name("recurring_interval"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.payment_options.is_active</code>.
     */
    public final TableField<PaymentOptionsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.payment_options.created_at</code>.
     */
    public final TableField<PaymentOptionsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.payment_options.updated_at</code>.
     */
    public final TableField<PaymentOptionsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private PaymentOptions(Name alias, Table<PaymentOptionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PaymentOptions(Name alias, Table<PaymentOptionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.payment_options</code> table reference
     */
    public PaymentOptions(String alias) {
        this(DSL.name(alias), PAYMENT_OPTIONS);
    }

    /**
     * Create an aliased <code>public.payment_options</code> table reference
     */
    public PaymentOptions(Name alias) {
        this(alias, PAYMENT_OPTIONS);
    }

    /**
     * Create a <code>public.payment_options</code> table reference
     */
    public PaymentOptions() {
        this(DSL.name("payment_options"), null);
    }

    public <O extends Record> PaymentOptions(Table<O> child, ForeignKey<O, PaymentOptionsRecord> key) {
        super(child, key, PAYMENT_OPTIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PaymentOptionsRecord, Long> getIdentity() {
        return (Identity<PaymentOptionsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PaymentOptionsRecord> getPrimaryKey() {
        return Keys.PAYMENT_OPTIONS_PKEY;
    }

    @Override
    public List<ForeignKey<PaymentOptionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PAYMENT_OPTIONS__FK_PAYMENT_OPTIONS_ASSET, Keys.PAYMENT_OPTIONS__FK_PAYMENT_OPTIONS_OWNER);
    }

    private transient Asset _asset;
    private transient Users _owner;

    public Asset asset() {
        if (_asset == null)
            _asset = new Asset(this, Keys.PAYMENT_OPTIONS__FK_PAYMENT_OPTIONS_ASSET);
        return _asset;
    }

    public Users owner() {
        if (_owner == null)
            _owner = new Users(this, Keys.PAYMENT_OPTIONS__FK_PAYMENT_OPTIONS_OWNER);
        return _owner;
    }

    @Override
    public PaymentOptions as(String alias) {
        return new PaymentOptions(DSL.name(alias), this);
    }

    @Override
    public PaymentOptions as(Name alias) {
        return new PaymentOptions(alias, this);
    }

    @Override
    public PaymentOptions as(Table<?> alias) {
        return new PaymentOptions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentOptions rename(String name) {
        return new PaymentOptions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentOptions rename(Name name) {
        return new PaymentOptions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PaymentOptions rename(Table<?> name) {
        return new PaymentOptions(name.getQualifiedName(), null);
    }

}
