/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables;


import com.rms.admin.persistence.Keys;
import com.rms.admin.persistence.Public;
import com.rms.admin.persistence.tables.records.PaymentsRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payments extends TableImpl<PaymentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.payments</code>
     */
    public static final Payments PAYMENTS = new Payments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentsRecord> getRecordType() {
        return PaymentsRecord.class;
    }

    /**
     * The column <code>public.payments.id</code>.
     */
    public final TableField<PaymentsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.payments.payment_option_id</code>.
     */
    public final TableField<PaymentsRecord, Long> PAYMENT_OPTION_ID = createField(DSL.name("payment_option_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.payments.asset_id</code>.
     */
    public final TableField<PaymentsRecord, Long> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.payments.tenant_user_id</code>.
     */
    public final TableField<PaymentsRecord, Long> TENANT_USER_ID = createField(DSL.name("tenant_user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.payments.owner_user_id</code>.
     */
    public final TableField<PaymentsRecord, Long> OWNER_USER_ID = createField(DSL.name("owner_user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.payments.amount</code>.
     */
    public final TableField<PaymentsRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "");

    /**
     * The column <code>public.payments.currency</code>.
     */
    public final TableField<PaymentsRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(3).nullable(false).defaultValue(DSL.field(DSL.raw("'USD'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.payments.status</code>.
     */
    public final TableField<PaymentsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.payments.stripe_checkout_session_id</code>.
     */
    public final TableField<PaymentsRecord, String> STRIPE_CHECKOUT_SESSION_ID = createField(DSL.name("stripe_checkout_session_id"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.payments.stripe_payment_intent_id</code>.
     */
    public final TableField<PaymentsRecord, String> STRIPE_PAYMENT_INTENT_ID = createField(DSL.name("stripe_payment_intent_id"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.payments.description</code>.
     */
    public final TableField<PaymentsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.payments.paid_at</code>.
     */
    public final TableField<PaymentsRecord, OffsetDateTime> PAID_AT = createField(DSL.name("paid_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.payments.created_at</code>.
     */
    public final TableField<PaymentsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.payments.updated_at</code>.
     */
    public final TableField<PaymentsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Payments(Name alias, Table<PaymentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Payments(Name alias, Table<PaymentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.payments</code> table reference
     */
    public Payments(String alias) {
        this(DSL.name(alias), PAYMENTS);
    }

    /**
     * Create an aliased <code>public.payments</code> table reference
     */
    public Payments(Name alias) {
        this(alias, PAYMENTS);
    }

    /**
     * Create a <code>public.payments</code> table reference
     */
    public Payments() {
        this(DSL.name("payments"), null);
    }

    public <O extends Record> Payments(Table<O> child, ForeignKey<O, PaymentsRecord> key) {
        super(child, key, PAYMENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PaymentsRecord, Long> getIdentity() {
        return (Identity<PaymentsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PaymentsRecord> getPrimaryKey() {
        return Keys.PAYMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<PaymentsRecord, ?>> getReferences() {
        return Arrays.asList(
                Keys.PAYMENTS__FK_PAYMENTS_PAYMENT_OPTION,
                Keys.PAYMENTS__FK_PAYMENTS_ASSET,
                Keys.PAYMENTS__FK_PAYMENTS_TENANT,
                Keys.PAYMENTS__FK_PAYMENTS_OWNER);
    }

    private transient PaymentOptions _paymentOption;
    private transient Asset _asset;
    private transient Users _tenant;
    private transient Users _owner;

    public PaymentOptions paymentOption() {
        if (_paymentOption == null)
            _paymentOption = new PaymentOptions(this, Keys.PAYMENTS__FK_PAYMENTS_PAYMENT_OPTION);
        return _paymentOption;
    }

    public Asset asset() {
        if (_asset == null)
            _asset = new Asset(this, Keys.PAYMENTS__FK_PAYMENTS_ASSET);
        return _asset;
    }

    public Users tenant() {
        if (_tenant == null)
            _tenant = new Users(this, Keys.PAYMENTS__FK_PAYMENTS_TENANT);
        return _tenant;
    }

    public Users owner() {
        if (_owner == null)
            _owner = new Users(this, Keys.PAYMENTS__FK_PAYMENTS_OWNER);
        return _owner;
    }

    @Override
    public Payments as(String alias) {
        return new Payments(DSL.name(alias), this);
    }

    @Override
    public Payments as(Name alias) {
        return new Payments(alias, this);
    }

    @Override
    public Payments as(Table<?> alias) {
        return new Payments(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(String name) {
        return new Payments(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(Name name) {
        return new Payments(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Payments rename(Table<?> name) {
        return new Payments(name.getQualifiedName(), null);
    }

}
