/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence;


import com.rms.admin.persistence.tables.Address;
import com.rms.admin.persistence.tables.Amenities;
import com.rms.admin.persistence.tables.AmenitiesAssetMapping;
import com.rms.admin.persistence.tables.Asset;
import com.rms.admin.persistence.tables.AssetImageMapping;
import com.rms.admin.persistence.tables.AssetTenantMapping;
import com.rms.admin.persistence.tables.AssetTenantRequest;
import com.rms.admin.persistence.tables.Category;
import com.rms.admin.persistence.tables.EmailTemplates;
import com.rms.admin.persistence.tables.FlywaySchemaHistory;
import com.rms.admin.persistence.tables.Images;
import com.rms.admin.persistence.tables.NotificationTemplates;
import com.rms.admin.persistence.tables.Notifications;
import com.rms.admin.persistence.tables.PaymentOptions;
import com.rms.admin.persistence.tables.Payments;
import com.rms.admin.persistence.tables.Roles;
import com.rms.admin.persistence.tables.Users;
import com.rms.admin.persistence.tables.records.AddressRecord;
import com.rms.admin.persistence.tables.records.AmenitiesAssetMappingRecord;
import com.rms.admin.persistence.tables.records.AmenitiesRecord;
import com.rms.admin.persistence.tables.records.AssetImageMappingRecord;
import com.rms.admin.persistence.tables.records.AssetRecord;
import com.rms.admin.persistence.tables.records.AssetTenantMappingRecord;
import com.rms.admin.persistence.tables.records.AssetTenantRequestRecord;
import com.rms.admin.persistence.tables.records.CategoryRecord;
import com.rms.admin.persistence.tables.records.EmailTemplatesRecord;
import com.rms.admin.persistence.tables.records.FlywaySchemaHistoryRecord;
import com.rms.admin.persistence.tables.records.ImagesRecord;
import com.rms.admin.persistence.tables.records.NotificationTemplatesRecord;
import com.rms.admin.persistence.tables.records.NotificationsRecord;
import com.rms.admin.persistence.tables.records.PaymentOptionsRecord;
import com.rms.admin.persistence.tables.records.PaymentsRecord;
import com.rms.admin.persistence.tables.records.RolesRecord;
import com.rms.admin.persistence.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> ADDRESS_PKEY = Internal.createUniqueKey(Address.ADDRESS, DSL.name("address_pkey"), new TableField[] { Address.ADDRESS.ID }, true);
    public static final UniqueKey<AmenitiesRecord> AMENITIES_NAME_KEY = Internal.createUniqueKey(Amenities.AMENITIES, DSL.name("amenities_name_key"), new TableField[] { Amenities.AMENITIES.NAME }, true);
    public static final UniqueKey<AmenitiesRecord> AMENITIES_PKEY = Internal.createUniqueKey(Amenities.AMENITIES, DSL.name("amenities_pkey"), new TableField[] { Amenities.AMENITIES.ID }, true);
    public static final UniqueKey<AmenitiesAssetMappingRecord> AMENITIES_ASSET_MAPPING_PKEY = Internal.createUniqueKey(AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING, DSL.name("amenities_asset_mapping_pkey"), new TableField[] { AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING.ASSET_ID, AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING.ANOMALY_ID }, true);
    public static final UniqueKey<AssetRecord> ASSET_PKEY = Internal.createUniqueKey(Asset.ASSET, DSL.name("asset_pkey"), new TableField[] { Asset.ASSET.ID }, true);
    public static final UniqueKey<AssetImageMappingRecord> ASSET_IMAGE_MAPPING_PKEY = Internal.createUniqueKey(AssetImageMapping.ASSET_IMAGE_MAPPING, DSL.name("asset_image_mapping_pkey"), new TableField[] { AssetImageMapping.ASSET_IMAGE_MAPPING.ASSET_ID, AssetImageMapping.ASSET_IMAGE_MAPPING.IMAGE_ID }, true);
    public static final UniqueKey<AssetTenantMappingRecord> ASSET_TENANT_MAPPING_PKEY = Internal.createUniqueKey(AssetTenantMapping.ASSET_TENANT_MAPPING, DSL.name("asset_tenant_mapping_pkey"), new TableField[] { AssetTenantMapping.ASSET_TENANT_MAPPING.USER_ID, AssetTenantMapping.ASSET_TENANT_MAPPING.ASSET_ID }, true);
    public static final UniqueKey<AssetTenantRequestRecord> ASSET_TENANT_REQUEST_PKEY = Internal.createUniqueKey(AssetTenantRequest.ASSET_TENANT_REQUEST, DSL.name("asset_tenant_request_pkey"), new TableField[] { AssetTenantRequest.ASSET_TENANT_REQUEST.USER_ID, AssetTenantRequest.ASSET_TENANT_REQUEST.ASSET_ID }, true);
    public static final UniqueKey<CategoryRecord> CATEGORY_NAME_KEY = Internal.createUniqueKey(Category.CATEGORY, DSL.name("category_name_key"), new TableField[] { Category.CATEGORY.NAME }, true);
    public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = Internal.createUniqueKey(Category.CATEGORY, DSL.name("category_pkey"), new TableField[] { Category.CATEGORY.ID }, true);
    public static final UniqueKey<EmailTemplatesRecord> EMAIL_TEMPLATES_PKEY = Internal.createUniqueKey(EmailTemplates.EMAIL_TEMPLATES, DSL.name("email_templates_pkey"), new TableField[] { EmailTemplates.EMAIL_TEMPLATES.ID }, true);
    public static final UniqueKey<EmailTemplatesRecord> EMAIL_TEMPLATES_SUBJECT_KEY = Internal.createUniqueKey(EmailTemplates.EMAIL_TEMPLATES, DSL.name("email_templates_subject_key"), new TableField[] { EmailTemplates.EMAIL_TEMPLATES.SUBJECT }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<ImagesRecord> IMAGES_PKEY = Internal.createUniqueKey(Images.IMAGES, DSL.name("images_pkey"), new TableField[] { Images.IMAGES.ID }, true);
    public static final UniqueKey<NotificationTemplatesRecord> NOTIFICATION_TEMPLATES_PKEY = Internal.createUniqueKey(NotificationTemplates.NOTIFICATION_TEMPLATES, DSL.name("notification_templates_pkey"), new TableField[] { NotificationTemplates.NOTIFICATION_TEMPLATES.ID }, true);
    public static final UniqueKey<NotificationTemplatesRecord> NOTIFICATION_TEMPLATES_TITLE_KEY = Internal.createUniqueKey(NotificationTemplates.NOTIFICATION_TEMPLATES, DSL.name("notification_templates_title_key"), new TableField[] { NotificationTemplates.NOTIFICATION_TEMPLATES.TITLE }, true);
    public static final UniqueKey<NotificationsRecord> NOTIFICATIONS_PKEY = Internal.createUniqueKey(Notifications.NOTIFICATIONS, DSL.name("notifications_pkey"), new TableField[] { Notifications.NOTIFICATIONS.ID }, true);
    public static final UniqueKey<RolesRecord> ROLES_NAME_KEY = Internal.createUniqueKey(Roles.ROLES, DSL.name("roles_name_key"), new TableField[] { Roles.ROLES.NAME }, true);
    public static final UniqueKey<RolesRecord> ROLES_PKEY = Internal.createUniqueKey(Roles.ROLES, DSL.name("roles_pkey"), new TableField[] { Roles.ROLES.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<PaymentOptionsRecord> PAYMENT_OPTIONS_PKEY = Internal.createUniqueKey(PaymentOptions.PAYMENT_OPTIONS, DSL.name("payment_options_pkey"), new TableField[] { PaymentOptions.PAYMENT_OPTIONS.ID }, true);
    public static final UniqueKey<PaymentsRecord> PAYMENTS_PKEY = Internal.createUniqueKey(Payments.PAYMENTS, DSL.name("payments_pkey"), new TableField[] { Payments.PAYMENTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AmenitiesAssetMappingRecord, AmenitiesRecord> AMENITIES_ASSET_MAPPING__FK_AMENITIES_ASSET_MAPPING_ANOMALY = Internal.createForeignKey(AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING, DSL.name("fk_amenities_asset_mapping_anomaly"), new TableField[] { AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING.ANOMALY_ID }, Keys.AMENITIES_PKEY, new TableField[] { Amenities.AMENITIES.ID }, true);
    public static final ForeignKey<AmenitiesAssetMappingRecord, AssetRecord> AMENITIES_ASSET_MAPPING__FK_AMENITIES_ASSET_MAPPING_ASSET = Internal.createForeignKey(AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING, DSL.name("fk_amenities_asset_mapping_asset"), new TableField[] { AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING.ASSET_ID }, Keys.ASSET_PKEY, new TableField[] { Asset.ASSET.ID }, true);
    public static final ForeignKey<AssetRecord, CategoryRecord> ASSET__FK_ASSET_CATEGORY = Internal.createForeignKey(Asset.ASSET, DSL.name("fk_asset_category"), new TableField[] { Asset.ASSET.CATEGORY_ID }, Keys.CATEGORY_PKEY, new TableField[] { Category.CATEGORY.ID }, true);
    public static final ForeignKey<AssetRecord, AddressRecord> ASSET__FK_ASSET_LOCATION = Internal.createForeignKey(Asset.ASSET, DSL.name("fk_asset_location"), new TableField[] { Asset.ASSET.LOCATION }, Keys.ADDRESS_PKEY, new TableField[] { Address.ADDRESS.ID }, true);
    public static final ForeignKey<AssetRecord, UsersRecord> ASSET__FK_ASSET_OWNER = Internal.createForeignKey(Asset.ASSET, DSL.name("fk_asset_owner"), new TableField[] { Asset.ASSET.OWNER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<AssetImageMappingRecord, AssetRecord> ASSET_IMAGE_MAPPING__FK_ASSET_IMAGE_MAPPING_ASSET = Internal.createForeignKey(AssetImageMapping.ASSET_IMAGE_MAPPING, DSL.name("fk_asset_image_mapping_asset"), new TableField[] { AssetImageMapping.ASSET_IMAGE_MAPPING.ASSET_ID }, Keys.ASSET_PKEY, new TableField[] { Asset.ASSET.ID }, true);
    public static final ForeignKey<AssetImageMappingRecord, ImagesRecord> ASSET_IMAGE_MAPPING__FK_ASSET_IMAGE_MAPPING_IMAGE = Internal.createForeignKey(AssetImageMapping.ASSET_IMAGE_MAPPING, DSL.name("fk_asset_image_mapping_image"), new TableField[] { AssetImageMapping.ASSET_IMAGE_MAPPING.IMAGE_ID }, Keys.IMAGES_PKEY, new TableField[] { Images.IMAGES.ID }, true);
    public static final ForeignKey<AssetTenantMappingRecord, AssetRecord> ASSET_TENANT_MAPPING__FK_ASSET_TENANT_MAPPING_ASSET = Internal.createForeignKey(AssetTenantMapping.ASSET_TENANT_MAPPING, DSL.name("fk_asset_tenant_mapping_asset"), new TableField[] { AssetTenantMapping.ASSET_TENANT_MAPPING.ASSET_ID }, Keys.ASSET_PKEY, new TableField[] { Asset.ASSET.ID }, true);
    public static final ForeignKey<AssetTenantMappingRecord, UsersRecord> ASSET_TENANT_MAPPING__FK_ASSET_TENANT_MAPPING_USER = Internal.createForeignKey(AssetTenantMapping.ASSET_TENANT_MAPPING, DSL.name("fk_asset_tenant_mapping_user"), new TableField[] { AssetTenantMapping.ASSET_TENANT_MAPPING.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<AssetTenantRequestRecord, AssetRecord> ASSET_TENANT_REQUEST__FK_ASSET_TENANT_REQUEST_ASSET = Internal.createForeignKey(AssetTenantRequest.ASSET_TENANT_REQUEST, DSL.name("fk_asset_tenant_request_asset"), new TableField[] { AssetTenantRequest.ASSET_TENANT_REQUEST.ASSET_ID }, Keys.ASSET_PKEY, new TableField[] { Asset.ASSET.ID }, true);
    public static final ForeignKey<AssetTenantRequestRecord, UsersRecord> ASSET_TENANT_REQUEST__FK_ASSET_TENANT_REQUEST_USER = Internal.createForeignKey(AssetTenantRequest.ASSET_TENANT_REQUEST, DSL.name("fk_asset_tenant_request_user"), new TableField[] { AssetTenantRequest.ASSET_TENANT_REQUEST.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<NotificationsRecord, UsersRecord> NOTIFICATIONS__FK_NOTIFICATIONS_USER = Internal.createForeignKey(Notifications.NOTIFICATIONS, DSL.name("fk_notifications_user"), new TableField[] { Notifications.NOTIFICATIONS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PaymentOptionsRecord, AssetRecord> PAYMENT_OPTIONS__FK_PAYMENT_OPTIONS_ASSET = Internal.createForeignKey(PaymentOptions.PAYMENT_OPTIONS, DSL.name("fk_payment_options_asset"), new TableField[] { PaymentOptions.PAYMENT_OPTIONS.ASSET_ID }, Keys.ASSET_PKEY, new TableField[] { Asset.ASSET.ID }, true);
    public static final ForeignKey<PaymentOptionsRecord, UsersRecord> PAYMENT_OPTIONS__FK_PAYMENT_OPTIONS_OWNER = Internal.createForeignKey(PaymentOptions.PAYMENT_OPTIONS, DSL.name("fk_payment_options_owner"), new TableField[] { PaymentOptions.PAYMENT_OPTIONS.OWNER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PaymentsRecord, PaymentOptionsRecord> PAYMENTS__FK_PAYMENTS_PAYMENT_OPTION = Internal.createForeignKey(Payments.PAYMENTS, DSL.name("fk_payments_payment_option"), new TableField[] { Payments.PAYMENTS.PAYMENT_OPTION_ID }, Keys.PAYMENT_OPTIONS_PKEY, new TableField[] { PaymentOptions.PAYMENT_OPTIONS.ID }, true);
    public static final ForeignKey<PaymentsRecord, AssetRecord> PAYMENTS__FK_PAYMENTS_ASSET = Internal.createForeignKey(Payments.PAYMENTS, DSL.name("fk_payments_asset"), new TableField[] { Payments.PAYMENTS.ASSET_ID }, Keys.ASSET_PKEY, new TableField[] { Asset.ASSET.ID }, true);
    public static final ForeignKey<PaymentsRecord, UsersRecord> PAYMENTS__FK_PAYMENTS_TENANT = Internal.createForeignKey(Payments.PAYMENTS, DSL.name("fk_payments_tenant"), new TableField[] { Payments.PAYMENTS.TENANT_USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PaymentsRecord, UsersRecord> PAYMENTS__FK_PAYMENTS_OWNER = Internal.createForeignKey(Payments.PAYMENTS, DSL.name("fk_payments_owner"), new TableField[] { Payments.PAYMENTS.OWNER_USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<UsersRecord, AddressRecord> USERS__FK_USERS_ADDRESS = Internal.createForeignKey(Users.USERS, DSL.name("fk_users_address"), new TableField[] { Users.USERS.ADDRESS_ID }, Keys.ADDRESS_PKEY, new TableField[] { Address.ADDRESS.ID }, true);
    public static final ForeignKey<UsersRecord, ImagesRecord> USERS__FK_USERS_IMAGE = Internal.createForeignKey(Users.USERS, DSL.name("fk_users_image"), new TableField[] { Users.USERS.IMAGE_ID }, Keys.IMAGES_PKEY, new TableField[] { Images.IMAGES.ID }, true);
    public static final ForeignKey<UsersRecord, RolesRecord> USERS__FK_USERS_ROLE = Internal.createForeignKey(Users.USERS, DSL.name("fk_users_role"), new TableField[] { Users.USERS.ROLE_ID }, Keys.ROLES_PKEY, new TableField[] { Roles.ROLES.ID }, true);
}
