/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence;


import com.rms.admin.persistence.tables.Address;
import com.rms.admin.persistence.tables.Amenities;
import com.rms.admin.persistence.tables.AmenitiesAssetMapping;
import com.rms.admin.persistence.tables.Asset;
import com.rms.admin.persistence.tables.AssetImageMapping;
import com.rms.admin.persistence.tables.AssetTenantMapping;
import com.rms.admin.persistence.tables.AssetTenantRequest;
import com.rms.admin.persistence.tables.Category;
import com.rms.admin.persistence.tables.EmailTemplates;
import com.rms.admin.persistence.tables.FlywaySchemaHistory;
import com.rms.admin.persistence.tables.Images;
import com.rms.admin.persistence.tables.NotificationTemplates;
import com.rms.admin.persistence.tables.Notifications;
import com.rms.admin.persistence.tables.Roles;
import com.rms.admin.persistence.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.amenities</code>.
     */
    public final Amenities AMENITIES = Amenities.AMENITIES;

    /**
     * The table <code>public.amenities_asset_mapping</code>.
     */
    public final AmenitiesAssetMapping AMENITIES_ASSET_MAPPING = AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING;

    /**
     * The table <code>public.asset</code>.
     */
    public final Asset ASSET = Asset.ASSET;

    /**
     * The table <code>public.asset_image_mapping</code>.
     */
    public final AssetImageMapping ASSET_IMAGE_MAPPING = AssetImageMapping.ASSET_IMAGE_MAPPING;

    /**
     * The table <code>public.asset_tenant_mapping</code>.
     */
    public final AssetTenantMapping ASSET_TENANT_MAPPING = AssetTenantMapping.ASSET_TENANT_MAPPING;

    /**
     * The table <code>public.asset_tenant_request</code>.
     */
    public final AssetTenantRequest ASSET_TENANT_REQUEST = AssetTenantRequest.ASSET_TENANT_REQUEST;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.email_templates</code>.
     */
    public final EmailTemplates EMAIL_TEMPLATES = EmailTemplates.EMAIL_TEMPLATES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.images</code>.
     */
    public final Images IMAGES = Images.IMAGES;

    /**
     * The table <code>public.notification_templates</code>.
     */
    public final NotificationTemplates NOTIFICATION_TEMPLATES = NotificationTemplates.NOTIFICATION_TEMPLATES;

    /**
     * The table <code>public.notifications</code>.
     */
    public final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            Amenities.AMENITIES,
            AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING,
            Asset.ASSET,
            AssetImageMapping.ASSET_IMAGE_MAPPING,
            AssetTenantMapping.ASSET_TENANT_MAPPING,
            AssetTenantRequest.ASSET_TENANT_REQUEST,
            Category.CATEGORY,
            EmailTemplates.EMAIL_TEMPLATES,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Images.IMAGES,
            NotificationTemplates.NOTIFICATION_TEMPLATES,
            Notifications.NOTIFICATIONS,
            Roles.ROLES,
            Users.USERS
        );
    }
}
