/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence;


import com.rms.admin.persistence.tables.Address;
import com.rms.admin.persistence.tables.Amenities;
import com.rms.admin.persistence.tables.AmenitiesAssetMapping;
import com.rms.admin.persistence.tables.Asset;
import com.rms.admin.persistence.tables.AssetImageMapping;
import com.rms.admin.persistence.tables.AssetTenantMapping;
import com.rms.admin.persistence.tables.AssetTenantRequest;
import com.rms.admin.persistence.tables.Category;
import com.rms.admin.persistence.tables.EmailTemplates;
import com.rms.admin.persistence.tables.FlywaySchemaHistory;
import com.rms.admin.persistence.tables.Images;
import com.rms.admin.persistence.tables.NotificationTemplates;
import com.rms.admin.persistence.tables.Notifications;
import com.rms.admin.persistence.tables.PaymentOptions;
import com.rms.admin.persistence.tables.Payments;
import com.rms.admin.persistence.tables.Roles;
import com.rms.admin.persistence.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.amenities</code>.
     */
    public static final Amenities AMENITIES = Amenities.AMENITIES;

    /**
     * The table <code>public.amenities_asset_mapping</code>.
     */
    public static final AmenitiesAssetMapping AMENITIES_ASSET_MAPPING = AmenitiesAssetMapping.AMENITIES_ASSET_MAPPING;

    /**
     * The table <code>public.asset</code>.
     */
    public static final Asset ASSET = Asset.ASSET;

    /**
     * The table <code>public.asset_image_mapping</code>.
     */
    public static final AssetImageMapping ASSET_IMAGE_MAPPING = AssetImageMapping.ASSET_IMAGE_MAPPING;

    /**
     * The table <code>public.asset_tenant_mapping</code>.
     */
    public static final AssetTenantMapping ASSET_TENANT_MAPPING = AssetTenantMapping.ASSET_TENANT_MAPPING;

    /**
     * The table <code>public.asset_tenant_request</code>.
     */
    public static final AssetTenantRequest ASSET_TENANT_REQUEST = AssetTenantRequest.ASSET_TENANT_REQUEST;

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.email_templates</code>.
     */
    public static final EmailTemplates EMAIL_TEMPLATES = EmailTemplates.EMAIL_TEMPLATES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.images</code>.
     */
    public static final Images IMAGES = Images.IMAGES;

    /**
     * The table <code>public.notification_templates</code>.
     */
    public static final NotificationTemplates NOTIFICATION_TEMPLATES = NotificationTemplates.NOTIFICATION_TEMPLATES;

    /**
     * The table <code>public.notifications</code>.
     */
    public static final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>public.payment_options</code>.
     */
    public static final PaymentOptions PAYMENT_OPTIONS = PaymentOptions.PAYMENT_OPTIONS;

    /**
     * The table <code>public.payments</code>.
     */
    public static final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
