/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IAddress;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements IAddress {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String localAddress;
    private String city;
    private String state;
    private String country;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public Address() {}

    public Address(IAddress value) {
        this.id = value.getId();
        this.localAddress = value.getLocalAddress();
        this.city = value.getCity();
        this.state = value.getState();
        this.country = value.getCountry();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public Address(
        Long id,
        String localAddress,
        String city,
        String state,
        String country,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.localAddress = localAddress;
        this.city = city;
        this.state = state;
        this.country = country;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.address.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.address.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.address.local_address</code>.
     */
    @Override
    public String getLocalAddress() {
        return this.localAddress;
    }

    /**
     * Setter for <code>public.address.local_address</code>.
     */
    @Override
    public void setLocalAddress(String localAddress) {
        this.localAddress = localAddress;
    }

    /**
     * Getter for <code>public.address.city</code>.
     */
    @Override
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.address.city</code>.
     */
    @Override
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>public.address.state</code>.
     */
    @Override
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>public.address.state</code>.
     */
    @Override
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Getter for <code>public.address.country</code>.
     */
    @Override
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>public.address.country</code>.
     */
    @Override
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for <code>public.address.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.address.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.address.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.address.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Address other = (Address) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.localAddress == null) {
            if (other.localAddress != null)
                return false;
        }
        else if (!this.localAddress.equals(other.localAddress))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.country == null) {
            if (other.country != null)
                return false;
        }
        else if (!this.country.equals(other.country))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.localAddress == null) ? 0 : this.localAddress.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(localAddress);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(country);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAddress from) {
        setId(from.getId());
        setLocalAddress(from.getLocalAddress());
        setCity(from.getCity());
        setState(from.getState());
        setCountry(from.getCountry());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    @Override
    public <E extends IAddress> E into(E into) {
        into.from(this);
        return into;
    }
}
