/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IAmenitiesAssetMapping;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AmenitiesAssetMapping implements IAmenitiesAssetMapping {

    private static final long serialVersionUID = 1L;

    private Long assetId;
    private Long anomalyId;

    public AmenitiesAssetMapping() {}

    public AmenitiesAssetMapping(IAmenitiesAssetMapping value) {
        this.assetId = value.getAssetId();
        this.anomalyId = value.getAnomalyId();
    }

    public AmenitiesAssetMapping(
        Long assetId,
        Long anomalyId
    ) {
        this.assetId = assetId;
        this.anomalyId = anomalyId;
    }

    /**
     * Getter for <code>public.amenities_asset_mapping.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return this.assetId;
    }

    /**
     * Setter for <code>public.amenities_asset_mapping.asset_id</code>.
     */
    @Override
    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    /**
     * Getter for <code>public.amenities_asset_mapping.anomaly_id</code>.
     */
    @Override
    public Long getAnomalyId() {
        return this.anomalyId;
    }

    /**
     * Setter for <code>public.amenities_asset_mapping.anomaly_id</code>.
     */
    @Override
    public void setAnomalyId(Long anomalyId) {
        this.anomalyId = anomalyId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AmenitiesAssetMapping other = (AmenitiesAssetMapping) obj;
        if (this.assetId == null) {
            if (other.assetId != null)
                return false;
        }
        else if (!this.assetId.equals(other.assetId))
            return false;
        if (this.anomalyId == null) {
            if (other.anomalyId != null)
                return false;
        }
        else if (!this.anomalyId.equals(other.anomalyId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.assetId == null) ? 0 : this.assetId.hashCode());
        result = prime * result + ((this.anomalyId == null) ? 0 : this.anomalyId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AmenitiesAssetMapping (");

        sb.append(assetId);
        sb.append(", ").append(anomalyId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAmenitiesAssetMapping from) {
        setAssetId(from.getAssetId());
        setAnomalyId(from.getAnomalyId());
    }

    @Override
    public <E extends IAmenitiesAssetMapping> E into(E into) {
        into.from(this);
        return into;
    }
}
