/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IAssetTenantMapping;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetTenantMapping implements IAssetTenantMapping {

    private static final long serialVersionUID = 1L;

    private Long userId;
    private Long assetId;

    public AssetTenantMapping() {}

    public AssetTenantMapping(IAssetTenantMapping value) {
        this.userId = value.getUserId();
        this.assetId = value.getAssetId();
    }

    public AssetTenantMapping(
        Long userId,
        Long assetId
    ) {
        this.userId = userId;
        this.assetId = assetId;
    }

    /**
     * Getter for <code>public.asset_tenant_mapping.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.asset_tenant_mapping.user_id</code>.
     */
    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.asset_tenant_mapping.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return this.assetId;
    }

    /**
     * Setter for <code>public.asset_tenant_mapping.asset_id</code>.
     */
    @Override
    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AssetTenantMapping other = (AssetTenantMapping) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.assetId == null) {
            if (other.assetId != null)
                return false;
        }
        else if (!this.assetId.equals(other.assetId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.assetId == null) ? 0 : this.assetId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetTenantMapping (");

        sb.append(userId);
        sb.append(", ").append(assetId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetTenantMapping from) {
        setUserId(from.getUserId());
        setAssetId(from.getAssetId());
    }

    @Override
    public <E extends IAssetTenantMapping> E into(E into) {
        into.from(this);
        return into;
    }
}
