/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IAssetImageMapping;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetImageMapping implements IAssetImageMapping {

    private static final long serialVersionUID = 1L;

    private Long assetId;
    private Long imageId;

    public AssetImageMapping() {}

    public AssetImageMapping(IAssetImageMapping value) {
        this.assetId = value.getAssetId();
        this.imageId = value.getImageId();
    }

    public AssetImageMapping(
        Long assetId,
        Long imageId
    ) {
        this.assetId = assetId;
        this.imageId = imageId;
    }

    /**
     * Getter for <code>public.asset_image_mapping.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return this.assetId;
    }

    /**
     * Setter for <code>public.asset_image_mapping.asset_id</code>.
     */
    @Override
    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    /**
     * Getter for <code>public.asset_image_mapping.image_id</code>.
     */
    @Override
    public Long getImageId() {
        return this.imageId;
    }

    /**
     * Setter for <code>public.asset_image_mapping.image_id</code>.
     */
    @Override
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AssetImageMapping other = (AssetImageMapping) obj;
        if (this.assetId == null) {
            if (other.assetId != null)
                return false;
        }
        else if (!this.assetId.equals(other.assetId))
            return false;
        if (this.imageId == null) {
            if (other.imageId != null)
                return false;
        }
        else if (!this.imageId.equals(other.imageId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.assetId == null) ? 0 : this.assetId.hashCode());
        result = prime * result + ((this.imageId == null) ? 0 : this.imageId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetImageMapping (");

        sb.append(assetId);
        sb.append(", ").append(imageId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetImageMapping from) {
        setAssetId(from.getAssetId());
        setImageId(from.getImageId());
    }

    @Override
    public <E extends IAssetImageMapping> E into(E into) {
        into.from(this);
        return into;
    }
}
