/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IAsset;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asset implements IAsset {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String title;
    private String description;
    private Long capacity;
    private BigDecimal rent;
    private JSONB tags;
    private Long categoryId;
    private Long ownerId;
    private Long location;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public Asset() {}

    public Asset(IAsset value) {
        this.id = value.getId();
        this.title = value.getTitle();
        this.description = value.getDescription();
        this.capacity = value.getCapacity();
        this.rent = value.getRent();
        this.tags = value.getTags();
        this.categoryId = value.getCategoryId();
        this.ownerId = value.getOwnerId();
        this.location = value.getLocation();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public Asset(
        Long id,
        String title,
        String description,
        Long capacity,
        BigDecimal rent,
        JSONB tags,
        Long categoryId,
        Long ownerId,
        Long location,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.capacity = capacity;
        this.rent = rent;
        this.tags = tags;
        this.categoryId = categoryId;
        this.ownerId = ownerId;
        this.location = location;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.asset.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.asset.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.asset.title</code>.
     */
    @Override
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.asset.title</code>.
     */
    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.asset.description</code>.
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.asset.description</code>.
     */
    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.asset.capacity</code>.
     */
    @Override
    public Long getCapacity() {
        return this.capacity;
    }

    /**
     * Setter for <code>public.asset.capacity</code>.
     */
    @Override
    public void setCapacity(Long capacity) {
        this.capacity = capacity;
    }

    /**
     * Getter for <code>public.asset.rent</code>.
     */
    @Override
    public BigDecimal getRent() {
        return this.rent;
    }

    /**
     * Setter for <code>public.asset.rent</code>.
     */
    @Override
    public void setRent(BigDecimal rent) {
        this.rent = rent;
    }

    /**
     * Getter for <code>public.asset.tags</code>.
     */
    @Override
    public JSONB getTags() {
        return this.tags;
    }

    /**
     * Setter for <code>public.asset.tags</code>.
     */
    @Override
    public void setTags(JSONB tags) {
        this.tags = tags;
    }

    /**
     * Getter for <code>public.asset.category_id</code>.
     */
    @Override
    public Long getCategoryId() {
        return this.categoryId;
    }

    /**
     * Setter for <code>public.asset.category_id</code>.
     */
    @Override
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Getter for <code>public.asset.owner_id</code>.
     */
    @Override
    public Long getOwnerId() {
        return this.ownerId;
    }

    /**
     * Setter for <code>public.asset.owner_id</code>.
     */
    @Override
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * Getter for <code>public.asset.location</code>.
     */
    @Override
    public Long getLocation() {
        return this.location;
    }

    /**
     * Setter for <code>public.asset.location</code>.
     */
    @Override
    public void setLocation(Long location) {
        this.location = location;
    }

    /**
     * Getter for <code>public.asset.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.asset.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.asset.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.asset.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Asset other = (Asset) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.capacity == null) {
            if (other.capacity != null)
                return false;
        }
        else if (!this.capacity.equals(other.capacity))
            return false;
        if (this.rent == null) {
            if (other.rent != null)
                return false;
        }
        else if (!this.rent.equals(other.rent))
            return false;
        if (this.tags == null) {
            if (other.tags != null)
                return false;
        }
        else if (!this.tags.equals(other.tags))
            return false;
        if (this.categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!this.categoryId.equals(other.categoryId))
            return false;
        if (this.ownerId == null) {
            if (other.ownerId != null)
                return false;
        }
        else if (!this.ownerId.equals(other.ownerId))
            return false;
        if (this.location == null) {
            if (other.location != null)
                return false;
        }
        else if (!this.location.equals(other.location))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.capacity == null) ? 0 : this.capacity.hashCode());
        result = prime * result + ((this.rent == null) ? 0 : this.rent.hashCode());
        result = prime * result + ((this.tags == null) ? 0 : this.tags.hashCode());
        result = prime * result + ((this.categoryId == null) ? 0 : this.categoryId.hashCode());
        result = prime * result + ((this.ownerId == null) ? 0 : this.ownerId.hashCode());
        result = prime * result + ((this.location == null) ? 0 : this.location.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Asset (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(capacity);
        sb.append(", ").append(rent);
        sb.append(", ").append(tags);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(location);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAsset from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setDescription(from.getDescription());
        setCapacity(from.getCapacity());
        setRent(from.getRent());
        setTags(from.getTags());
        setCategoryId(from.getCategoryId());
        setOwnerId(from.getOwnerId());
        setLocation(from.getLocation());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    @Override
    public <E extends IAsset> E into(E into) {
        into.from(this);
        return into;
    }
}
