/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IAssetTenantRequest;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssetTenantRequest implements IAssetTenantRequest {

    private static final long serialVersionUID = 1L;

    private Long userId;
    private Long assetId;
    private String type;
    private OffsetDateTime createdAt;

    public AssetTenantRequest() {}

    public AssetTenantRequest(IAssetTenantRequest value) {
        this.userId = value.getUserId();
        this.assetId = value.getAssetId();
        this.type = value.getType();
        this.createdAt = value.getCreatedAt();
    }

    public AssetTenantRequest(
        Long userId,
        Long assetId,
        String type,
        OffsetDateTime createdAt
    ) {
        this.userId = userId;
        this.assetId = assetId;
        this.type = type;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.asset_tenant_request.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.asset_tenant_request.user_id</code>.
     */
    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.asset_tenant_request.asset_id</code>.
     */
    @Override
    public Long getAssetId() {
        return this.assetId;
    }

    /**
     * Setter for <code>public.asset_tenant_request.asset_id</code>.
     */
    @Override
    public void setAssetId(Long assetId) {
        this.assetId = assetId;
    }

    /**
     * Getter for <code>public.asset_tenant_request.type</code>.
     */
    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.asset_tenant_request.type</code>.
     */
    @Override
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.asset_tenant_request.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.asset_tenant_request.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AssetTenantRequest other = (AssetTenantRequest) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.assetId == null) {
            if (other.assetId != null)
                return false;
        }
        else if (!this.assetId.equals(other.assetId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.assetId == null) ? 0 : this.assetId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AssetTenantRequest (");

        sb.append(userId);
        sb.append(", ").append(assetId);
        sb.append(", ").append(type);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAssetTenantRequest from) {
        setUserId(from.getUserId());
        setAssetId(from.getAssetId());
        setType(from.getType());
        setCreatedAt(from.getCreatedAt());
    }

    @Override
    public <E extends IAssetTenantRequest> E into(E into) {
        into.from(this);
        return into;
    }
}
