/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IEmailTemplates;

import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailTemplates implements IEmailTemplates {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String subject;
    private String template;
    private JSONB placeholderValues;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public EmailTemplates() {}

    public EmailTemplates(IEmailTemplates value) {
        this.id = value.getId();
        this.subject = value.getSubject();
        this.template = value.getTemplate();
        this.placeholderValues = value.getPlaceholderValues();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public EmailTemplates(
        Long id,
        String subject,
        String template,
        JSONB placeholderValues,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.subject = subject;
        this.template = template;
        this.placeholderValues = placeholderValues;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.email_templates.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.email_templates.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.email_templates.subject</code>.
     */
    @Override
    public String getSubject() {
        return this.subject;
    }

    /**
     * Setter for <code>public.email_templates.subject</code>.
     */
    @Override
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * Getter for <code>public.email_templates.template</code>.
     */
    @Override
    public String getTemplate() {
        return this.template;
    }

    /**
     * Setter for <code>public.email_templates.template</code>.
     */
    @Override
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * Getter for <code>public.email_templates.placeholder_values</code>.
     */
    @Override
    public JSONB getPlaceholderValues() {
        return this.placeholderValues;
    }

    /**
     * Setter for <code>public.email_templates.placeholder_values</code>.
     */
    @Override
    public void setPlaceholderValues(JSONB placeholderValues) {
        this.placeholderValues = placeholderValues;
    }

    /**
     * Getter for <code>public.email_templates.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.email_templates.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.email_templates.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.email_templates.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EmailTemplates other = (EmailTemplates) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.subject == null) {
            if (other.subject != null)
                return false;
        }
        else if (!this.subject.equals(other.subject))
            return false;
        if (this.template == null) {
            if (other.template != null)
                return false;
        }
        else if (!this.template.equals(other.template))
            return false;
        if (this.placeholderValues == null) {
            if (other.placeholderValues != null)
                return false;
        }
        else if (!this.placeholderValues.equals(other.placeholderValues))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.subject == null) ? 0 : this.subject.hashCode());
        result = prime * result + ((this.template == null) ? 0 : this.template.hashCode());
        result = prime * result + ((this.placeholderValues == null) ? 0 : this.placeholderValues.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EmailTemplates (");

        sb.append(id);
        sb.append(", ").append(subject);
        sb.append(", ").append(template);
        sb.append(", ").append(placeholderValues);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IEmailTemplates from) {
        setId(from.getId());
        setSubject(from.getSubject());
        setTemplate(from.getTemplate());
        setPlaceholderValues(from.getPlaceholderValues());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    @Override
    public <E extends IEmailTemplates> E into(E into) {
        into.from(this);
        return into;
    }
}
