/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.pojos;


import com.rms.admin.persistence.tables.interfaces.IUsers;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements IUsers {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long imageId;
    private String name;
    private String email;
    private String password;
    private String jwtSecret;
    private String phoneNo;
    private Long roleId;
    private Long addressId;
    private Boolean isVerified;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public Users() {}

    public Users(IUsers value) {
        this.id = value.getId();
        this.imageId = value.getImageId();
        this.name = value.getName();
        this.email = value.getEmail();
        this.password = value.getPassword();
        this.jwtSecret = value.getJwtSecret();
        this.phoneNo = value.getPhoneNo();
        this.roleId = value.getRoleId();
        this.addressId = value.getAddressId();
        this.isVerified = value.getIsVerified();
        this.createdAt = value.getCreatedAt();
        this.updatedAt = value.getUpdatedAt();
    }

    public Users(
        Long id,
        Long imageId,
        String name,
        String email,
        String password,
        String jwtSecret,
        String phoneNo,
        Long roleId,
        Long addressId,
        Boolean isVerified,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.imageId = imageId;
        this.name = name;
        this.email = email;
        this.password = password;
        this.jwtSecret = jwtSecret;
        this.phoneNo = phoneNo;
        this.roleId = roleId;
        this.addressId = addressId;
        this.isVerified = isVerified;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.users.id</code>.
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.users.image_id</code>.
     */
    @Override
    public Long getImageId() {
        return this.imageId;
    }

    /**
     * Setter for <code>public.users.image_id</code>.
     */
    @Override
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    @Override
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    @Override
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>public.users.jwt_secret</code>.
     */
    @Override
    public String getJwtSecret() {
        return this.jwtSecret;
    }

    /**
     * Setter for <code>public.users.jwt_secret</code>.
     */
    @Override
    public void setJwtSecret(String jwtSecret) {
        this.jwtSecret = jwtSecret;
    }

    /**
     * Getter for <code>public.users.phone_no</code>.
     */
    @Override
    public String getPhoneNo() {
        return this.phoneNo;
    }

    /**
     * Setter for <code>public.users.phone_no</code>.
     */
    @Override
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * Getter for <code>public.users.role_id</code>.
     */
    @Override
    public Long getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>public.users.role_id</code>.
     */
    @Override
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>public.users.address_id</code>.
     */
    @Override
    public Long getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>public.users.address_id</code>.
     */
    @Override
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * Getter for <code>public.users.is_verified</code>.
     */
    @Override
    public Boolean getIsVerified() {
        return this.isVerified;
    }

    /**
     * Setter for <code>public.users.is_verified</code>.
     */
    @Override
    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    @Override
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    @Override
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    @Override
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    @Override
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.imageId == null) {
            if (other.imageId != null)
                return false;
        }
        else if (!this.imageId.equals(other.imageId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.jwtSecret == null) {
            if (other.jwtSecret != null)
                return false;
        }
        else if (!this.jwtSecret.equals(other.jwtSecret))
            return false;
        if (this.phoneNo == null) {
            if (other.phoneNo != null)
                return false;
        }
        else if (!this.phoneNo.equals(other.phoneNo))
            return false;
        if (this.roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!this.roleId.equals(other.roleId))
            return false;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.isVerified == null) {
            if (other.isVerified != null)
                return false;
        }
        else if (!this.isVerified.equals(other.isVerified))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.imageId == null) ? 0 : this.imageId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.jwtSecret == null) ? 0 : this.jwtSecret.hashCode());
        result = prime * result + ((this.phoneNo == null) ? 0 : this.phoneNo.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.isVerified == null) ? 0 : this.isVerified.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(imageId);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(jwtSecret);
        sb.append(", ").append(phoneNo);
        sb.append(", ").append(roleId);
        sb.append(", ").append(addressId);
        sb.append(", ").append(isVerified);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUsers from) {
        setId(from.getId());
        setImageId(from.getImageId());
        setName(from.getName());
        setEmail(from.getEmail());
        setPassword(from.getPassword());
        setJwtSecret(from.getJwtSecret());
        setPhoneNo(from.getPhoneNo());
        setRoleId(from.getRoleId());
        setAddressId(from.getAddressId());
        setIsVerified(from.getIsVerified());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    @Override
    public <E extends IUsers> E into(E into) {
        into.from(this);
        return into;
    }
}
