/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAddress extends Serializable {

    /**
     * Setter for <code>public.address.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.address.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.address.local_address</code>.
     */
    public void setLocalAddress(String value);

    /**
     * Getter for <code>public.address.local_address</code>.
     */
    public String getLocalAddress();

    /**
     * Setter for <code>public.address.city</code>.
     */
    public void setCity(String value);

    /**
     * Getter for <code>public.address.city</code>.
     */
    public String getCity();

    /**
     * Setter for <code>public.address.state</code>.
     */
    public void setState(String value);

    /**
     * Getter for <code>public.address.state</code>.
     */
    public String getState();

    /**
     * Setter for <code>public.address.country</code>.
     */
    public void setCountry(String value);

    /**
     * Getter for <code>public.address.country</code>.
     */
    public String getCountry();

    /**
     * Setter for <code>public.address.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.address.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.address.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.address.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAddress
     */
    public void from(IAddress from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAddress
     */
    public <E extends IAddress> E into(E into);
}
