/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAmenitiesAssetMapping extends Serializable {

    /**
     * Setter for <code>public.amenities_asset_mapping.asset_id</code>.
     */
    public void setAssetId(Long value);

    /**
     * Getter for <code>public.amenities_asset_mapping.asset_id</code>.
     */
    public Long getAssetId();

    /**
     * Setter for <code>public.amenities_asset_mapping.anomaly_id</code>.
     */
    public void setAnomalyId(Long value);

    /**
     * Getter for <code>public.amenities_asset_mapping.anomaly_id</code>.
     */
    public Long getAnomalyId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAmenitiesAssetMapping
     */
    public void from(IAmenitiesAssetMapping from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAmenitiesAssetMapping
     */
    public <E extends IAmenitiesAssetMapping> E into(E into);
}
