/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAmenities extends Serializable {

    /**
     * Setter for <code>public.amenities.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.amenities.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.amenities.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.amenities.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.amenities.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.amenities.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.amenities.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.amenities.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAmenities
     */
    public void from(IAmenities from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAmenities
     */
    public <E extends IAmenities> E into(E into);
}
