/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAssetTenantMapping extends Serializable {

    /**
     * Setter for <code>public.asset_tenant_mapping.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>public.asset_tenant_mapping.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>public.asset_tenant_mapping.asset_id</code>.
     */
    public void setAssetId(Long value);

    /**
     * Getter for <code>public.asset_tenant_mapping.asset_id</code>.
     */
    public Long getAssetId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAssetTenantMapping
     */
    public void from(IAssetTenantMapping from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAssetTenantMapping
     */
    public <E extends IAssetTenantMapping> E into(E into);
}
