/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAssetTenantRequest extends Serializable {

    /**
     * Setter for <code>public.asset_tenant_request.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>public.asset_tenant_request.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>public.asset_tenant_request.asset_id</code>.
     */
    public void setAssetId(Long value);

    /**
     * Getter for <code>public.asset_tenant_request.asset_id</code>.
     */
    public Long getAssetId();

    /**
     * Setter for <code>public.asset_tenant_request.type</code>.
     */
    public void setType(String value);

    /**
     * Getter for <code>public.asset_tenant_request.type</code>.
     */
    public String getType();

    /**
     * Setter for <code>public.asset_tenant_request.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.asset_tenant_request.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAssetTenantRequest
     */
    public void from(IAssetTenantRequest from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAssetTenantRequest
     */
    public <E extends IAssetTenantRequest> E into(E into);
}
