/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAssetImageMapping extends Serializable {

    /**
     * Setter for <code>public.asset_image_mapping.asset_id</code>.
     */
    public void setAssetId(Long value);

    /**
     * Getter for <code>public.asset_image_mapping.asset_id</code>.
     */
    public Long getAssetId();

    /**
     * Setter for <code>public.asset_image_mapping.image_id</code>.
     */
    public void setImageId(Long value);

    /**
     * Getter for <code>public.asset_image_mapping.image_id</code>.
     */
    public Long getImageId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAssetImageMapping
     */
    public void from(IAssetImageMapping from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAssetImageMapping
     */
    public <E extends IAssetImageMapping> E into(E into);
}
