/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAsset extends Serializable {

    /**
     * Setter for <code>public.asset.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.asset.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.asset.title</code>.
     */
    public void setTitle(String value);

    /**
     * Getter for <code>public.asset.title</code>.
     */
    public String getTitle();

    /**
     * Setter for <code>public.asset.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>public.asset.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.asset.capacity</code>.
     */
    public void setCapacity(Long value);

    /**
     * Getter for <code>public.asset.capacity</code>.
     */
    public Long getCapacity();

    /**
     * Setter for <code>public.asset.rent</code>.
     */
    public void setRent(BigDecimal value);

    /**
     * Getter for <code>public.asset.rent</code>.
     */
    public BigDecimal getRent();

    /**
     * Setter for <code>public.asset.tags</code>.
     */
    public void setTags(JSONB value);

    /**
     * Getter for <code>public.asset.tags</code>.
     */
    public JSONB getTags();

    /**
     * Setter for <code>public.asset.category_id</code>.
     */
    public void setCategoryId(Long value);

    /**
     * Getter for <code>public.asset.category_id</code>.
     */
    public Long getCategoryId();

    /**
     * Setter for <code>public.asset.owner_id</code>.
     */
    public void setOwnerId(Long value);

    /**
     * Getter for <code>public.asset.owner_id</code>.
     */
    public Long getOwnerId();

    /**
     * Setter for <code>public.asset.location</code>.
     */
    public void setLocation(Long value);

    /**
     * Getter for <code>public.asset.location</code>.
     */
    public Long getLocation();

    /**
     * Setter for <code>public.asset.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.asset.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.asset.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.asset.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IAsset
     */
    public void from(IAsset from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IAsset
     */
    public <E extends IAsset> E into(E into);
}
