/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IEmailTemplates extends Serializable {

    /**
     * Setter for <code>public.email_templates.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.email_templates.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.email_templates.subject</code>.
     */
    public void setSubject(String value);

    /**
     * Getter for <code>public.email_templates.subject</code>.
     */
    public String getSubject();

    /**
     * Setter for <code>public.email_templates.template</code>.
     */
    public void setTemplate(String value);

    /**
     * Getter for <code>public.email_templates.template</code>.
     */
    public String getTemplate();

    /**
     * Setter for <code>public.email_templates.placeholder_values</code>.
     */
    public void setPlaceholderValues(JSONB value);

    /**
     * Getter for <code>public.email_templates.placeholder_values</code>.
     */
    public JSONB getPlaceholderValues();

    /**
     * Setter for <code>public.email_templates.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.email_templates.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.email_templates.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.email_templates.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IEmailTemplates
     */
    public void from(IEmailTemplates from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IEmailTemplates
     */
    public <E extends IEmailTemplates> E into(E into);
}
