/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IImages extends Serializable {

    /**
     * Setter for <code>public.images.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.images.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.images.key</code>.
     */
    public void setKey(String value);

    /**
     * Getter for <code>public.images.key</code>.
     */
    public String getKey();

    /**
     * Setter for <code>public.images.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.images.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.images.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.images.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IImages
     */
    public void from(IImages from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IImages
     */
    public <E extends IImages> E into(E into);
}
