/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface INotifications extends Serializable {

    /**
     * Setter for <code>public.notifications.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.notifications.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.notifications.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>public.notifications.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>public.notifications.message</code>.
     */
    public void setMessage(String value);

    /**
     * Getter for <code>public.notifications.message</code>.
     */
    public String getMessage();

    /**
     * Setter for <code>public.notifications.is_read</code>.
     */
    public void setIsRead(Boolean value);

    /**
     * Getter for <code>public.notifications.is_read</code>.
     */
    public Boolean getIsRead();

    /**
     * Setter for <code>public.notifications.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.notifications.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.notifications.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.notifications.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface INotifications
     */
    public void from(INotifications from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface INotifications
     */
    public <E extends INotifications> E into(E into);
}
