/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRoles extends Serializable {

    /**
     * Setter for <code>public.roles.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.roles.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.roles.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.roles.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.roles.description</code>.
     */
    public void setDescription(String value);

    /**
     * Getter for <code>public.roles.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.roles.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.roles.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.roles.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.roles.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IRoles
     */
    public void from(IRoles from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IRoles
     */
    public <E extends IRoles> E into(E into);
}
