/*
 * This file is generated by jOOQ.
 */
package com.rms.admin.persistence.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUsers extends Serializable {

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Long value);

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.users.image_id</code>.
     */
    public void setImageId(Long value);

    /**
     * Getter for <code>public.users.image_id</code>.
     */
    public Long getImageId();

    /**
     * Setter for <code>public.users.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>public.users.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.users.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>public.users.password</code>.
     */
    public void setPassword(String value);

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>public.users.jwt_secret</code>.
     */
    public void setJwtSecret(String value);

    /**
     * Getter for <code>public.users.jwt_secret</code>.
     */
    public String getJwtSecret();

    /**
     * Setter for <code>public.users.phone_no</code>.
     */
    public void setPhoneNo(String value);

    /**
     * Getter for <code>public.users.phone_no</code>.
     */
    public String getPhoneNo();

    /**
     * Setter for <code>public.users.role_id</code>.
     */
    public void setRoleId(Long value);

    /**
     * Getter for <code>public.users.role_id</code>.
     */
    public Long getRoleId();

    /**
     * Setter for <code>public.users.address_id</code>.
     */
    public void setAddressId(Long value);

    /**
     * Getter for <code>public.users.address_id</code>.
     */
    public Long getAddressId();

    /**
     * Setter for <code>public.users.is_verified</code>.
     */
    public void setIsVerified(Boolean value);

    /**
     * Getter for <code>public.users.is_verified</code>.
     */
    public Boolean getIsVerified();

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value);

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IUsers
     */
    public void from(IUsers from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IUsers
     */
    public <E extends IUsers> E into(E into);
}
